### ISSUE TITLE
feat: add `minimizable` and `maximizable` options

### ISSUE THREAD

**Issue by antoncda** [tauri-apps/tao#116]
Feature required where when alwaysOnTop is set to true, then even clicking on the app icon on the OS's task bar should not minimize the application and it stays always on top unless exited by the user.
Thanks, 
Donnie

**Comment by nothingismagick** [comment]
Do you mean always on top or non minimizable? That's two different things. I think I understand, but want to make sure your feature request is clear.

**Comment by antoncda** [comment]
i think its sort of an extra flavour of always on top, I've seen apps which just float on your desktop and wont minimize or quit unless disabled in the system tray, I guess this was done using C++ or C# but thought it would be a nice feature to add if possible. thank you

**Comment by antoncda** [comment]
To give an example. If we wish to create a tool bar which always floats, then clicking on the taskbar icon should not minimize it as it would hide and defeat its purpose. thanks.

**Comment by nothingismagick** [comment]
Sure, I've seen this in updaters on macos. It's aggressive and pisses me off, but a LOT less than when I restart my system after a month of uptime and discover an errant window from some process still there in the background.

Thanks

**Comment by antoncda** [comment]
I saw this option in Electron "skipTaskbar: true" this sort of solves the issue of app being un-minimizable whereby the app does not feature on the taskbar with this option therefore it is not minimizable if you disable the minimize button on your titlebar only enabling the close button if you wish.

**Comment by amrbashir** [comment]
This should stay un-minimizable feature request as we have skip_taskbar implemented already. I think it is possible on windows, linux seems to be a dead end and I don't know about macOS but I will keep this open until further investigation.

**Comment by wusyong** [comment]
we called `deiconify` on Linux when minimized is false.

**Comment by amrbashir** [comment]
yeah but that won't stop the user from clicking the icon in the taskbar/dock to minimize it. 

I think electron had `minimizable` and `maximizable` options, so I might have to dig into their source code.

**Comment by amrbashir** [comment]
After some digging around, `minimizable` and `maximizable` is possible on macOS and Windows, linux seems impossible unfortunately.
