### ISSUE TITLE
macOS: Focus Can't be Obtained After Making Visible

### ISSUE THREAD

**Issue by dfontana** [tauri-apps/tao#123]
**Issue:** Utilizing hotkeys to toggle a window's visibility & focus (in a tray app, for example) will not capture the application's focus.

**Expected Behavior:** A window should toggle to a visible state, and capture focus allowing it to be interacted with immediately (for things such as keyboard input, etc).

**Minimum Reproduction:**  On `MacOS 11.1 (20C69) Intel Core i5`, the following code can be pasted into the `examples/` and ran. 
<details>
  <summary>Minimum Reproducible Example</summary>

```rust
use tao::{
  accelerator::{Accelerator, SysMods},
  event::{Event, WindowEvent},
  event_loop::{ControlFlow, EventLoop},
  keyboard::KeyCode,
  platform::global_shortcut::ShortcutManager,
  window::WindowBuilder,
};

#[allow(clippy::single_match)]
fn main() {
  let event_loop = EventLoop::new();

  let window = WindowBuilder::new()
    .with_title("A fantastic window!")
    .with_inner_size(tao::dpi::LogicalSize::new(128.0, 128.0))
    .build(&event_loop)
    .unwrap();

  let shortcut_1 = Accelerator::new(SysMods::Shift, KeyCode::KeyB);
  let mut hotkey_manager = ShortcutManager::new(&event_loop);
  hotkey_manager.register(shortcut_1.clone()).unwrap();

  event_loop.run(move |event, _, control_flow| {
    *control_flow = ControlFlow::Wait;
    match event {
      Event::GlobalShortcutEvent(hotkey_id) if hotkey_id == shortcut_1.clone().id() => {
        if window.is_visible() {
          println!("Making invisible");
          window.set_visible(false);
        } else {
          println!("Making Visible and Focused");
          window.set_visible(true);
          window.set_focus();
        }
      }
      Event::WindowEvent {
        event: WindowEvent::CloseRequested,
        window_id,
        ..
      } if window_id == window.id() => *control_flow = ControlFlow::Exit,
      Event::MainEventsCleared => {
        window.request_redraw();
      }
      _ => (),
    }
  });
}
```
</details>

Alternatively, here's a short video:

https://user-images.githubusercontent.com/15203135/124858222-a6f55700-df7b-11eb-831f-b952a60b0a9d.mov

**Potential Root Cause**
- Appears to be a race condition in the Global Dispatch functionality. [set_focus handler on window](https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/macos/window.rs#L453-L471) will only execute if the window is considered visible, while the `set_visible` handler is submitting an [async event](https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/macos/util/async.rs#L196). The async event does not appear to complete in time for the `set_focus` call, thus the `set_focus` never attempts to emit a focus event since the window is considered `is_visible == NO`
- Removing the visibility check on `set_focus` can resolve the problem, but potentially [introduces some other problem](https://github.com/tauri-apps/tao/pull/73).
- Attempting to change the `exec_async`  to `exec_sync` on `make_key_and_order_front_async` triggered an `Illegal Hardware Instruction` on my machine; but I'm not that experienced with this system.

**Comment by wusyong** [comment]
I think we added checks to prevent some bugs on other platforms but check it on all for integrity.
I'll do some more tests between platforms to confirm which checks could be removed.
