### ISSUE TITLE
Feature Request: Constrain window width, but not window height.

### ISSUE THREAD

**Issue by yiar** [tauri-apps/tao#138]
See discussion including screenshots at Discord.

https://discord.com/channels/616186924390023171/625037620996734986/866688857139314729

"setting maxWidth breaks the vertical resizing" ... "also enforces the minHeight as its maxHeight"

My project need to be able to keep approximately the same width, but adjust height during runtime. E.g. like Apple Music for macOS does. It can be resized horizontally, but only up to a maxWidth. However height can be as high as you'd like.

**Comment by FabianLars** [comment]
<s>
Copy-pasting my message from discord:

There is still a bug tho i think.
If you set a maxWidth and a minHeight you get a window with maxWidth and a MAXHeight with the value of the minHeight.
If you then set a maxHeight it doesn't have visual consequences, but the vertical resizing stops working.
Try adding this to the api example (or whatever):
```
"maxWidth": 1000,
"minWidth": 10,
"minHeight": 100,
"maxHeight": 2000,
"resizable": true
```
</s> 

Edit: apparently it was a bug at Tauri-level https://github.com/tauri-apps/tauri/pull/2247
