### ISSUE TITLE
What is valid for key Space as accelerator name?

### ISSUE THREAD

**Issue by tolgaerdonmez** [tauri-apps/tao#147]
System: macOS Big Sur 11.4

## Code/Problem

```rs
CustomMenuItem::new("start_stop".to_string(), "Start/Stop").accelerator("Space");
```

Giving name Space won't work also tried, "space", " ", "_"

## Output
```sh
no key equivalent for Accelerator { id: Some(AcceleratorId(39259)), mods: (empty), key: Space }
```

**Comment by lemarier** [comment]
hi, @tolgaerdonmez I've found the issue, but I still can't figure how to register only the Space for a menu accelerator. Do you have an electron example where it works?

The Space key code will be added by PR https://github.com/tauri-apps/tao/pull/148

For example, this won't work;
```rust
CustomMenuItem::new("start_stop".to_string(), "Start/Stop").accelerator("Space");
```

but this one works fine;
```rust
CustomMenuItem::new("start_stop".to_string(), "Start/Stop").accelerator("F6");
```

and this work too;
```rust
CustomMenuItem::new("start_stop".to_string(), "Start/Stop").accelerator("Cmd+Space");
```

**Comment by tolgaerdonmez** [comment]
Unfortunately it still isn't working, I'm also having problems with `escape` too, I'm on macos Big Sur 11.4 maybe its about that, idk.

**Comment by tolgaerdonmez** [comment]
@lemarier [here](https://github.com/tolgaerdonmez/metronome/blob/087502ff62d6fb0a2a83d1b066ba6f4e34be2652/src/electron/windows/MainWindow.js#L68) is the electron version which is working,

**Comment by lemarier** [comment]
@tolgaerdonmez can you try to add this in your Cargo.toml;

```toml
[patch.crates-io]
tao = { git = "https://github.com/tauri-apps/tao", branch = "dev" }
```

do a `cargo update` and try with `Space` and `Esc` KeyCode
Let me know if it works

Thanks

**Comment by cosoc** [comment]
`    Invalid accelerators

**Comment by cosoc** [comment]
I found that all single keys cannot register shortcut keys. When using Electron, any key can be bound. I hope it can be resolved as soon as possible
