### ISSUE TITLE
How to emit event into frontend with menu items ? 

### ISSUE THREAD

**Issue by tolgaerdonmez** [tauri-apps/tao#149]
## Problem
As far as the docs and the source code says I'm not able to communicate between backend and frontend via menu actions, which is very crucial yet unmentioned.

```rs
tauri::Builder::default()
   ....
```

For example `.on_system_tray_event(handler)` the handler accepts the `app, event` parameters but not in `.on_menu_event(handler)` which causes my problem.

**Comment by lemarier** [comment]
You can do something like;
```rust
.on_menu_event(|event| {
      let window = event.window();
      match window.set_focus() {
        Ok(_) => {
          println!("focus set successfully");
        }
        Err(err) => {
          println!("failed to set focus: {:?}", err);
        }
      }
    })
```

The menu_event is bonded to a Window, where the System tray menu isn't. That's the main reason the signature is different.

Also, with `window` you can by example, `window.emit(event, payload)` to communicate with webview

**Comment by tolgaerdonmez** [comment]
@lemarier ohhh thanks very much
