### ISSUE TITLE
bug: incorrect monitor size on linux

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tao#175]
from @FabianLars on discord:
> i also started looking into the center thingy and it looks like the root cause is an incorrectly reported monitor size (470,300 instead of 1440p on my end), which causes a attempt to subtract with overflow error. Unfortunately i have to start cooking now sweat_smile

**Comment by amrbashir** [comment]
I think we should use `gdk::monitor::workarea` or `gdk::monitor::geometry`.
