### ISSUE TITLE
feat: `window.set_ignore_mouse_events`

### ISSUE THREAD

**Issue by pankerit** [tauri-apps/tao#184]
Possibility to click through window.
In case window is transparent I would like to pass it.

**Comment by slauko** [comment]
any news on this? 
would love to swap from electron to tauri for my apps, i basically only need a switch for mouse_events, 
would do it manually on mouse enter leave events in js/react of the divs i need the mouse to be enabled, so i dont even need the "auto transparency" - detection :)

**Comment by amrbashir** [comment]
I can implement this soon but it won't be exposed in tauri until v2.

**Comment by vdvman1** [comment]
> would do it manually on mouse enter leave events

But if the mouse events are disabled, then those events wouldn't trigger, so I don't think it's that simple

**Comment by slauko** [comment]
> > would do it manually on mouse enter leave events
> 
> But if the mouse events are disabled, then those events wouldn't trigger, so I don't think it's that simple

as far as i know electron has something called forwarding .. so you still can "catch" the events manually if u want to, but their default behaviour is disabled

```
win.setIgnoreMouseEvents(ignore[, options])
ignore boolean
options Object (optional)
forward boolean (optional) macOS Windows - If true, forwards mouse move messages to Chromium, enabling mouse related events such as mouseleave. Only used when ignore is true. If ignore is false, forwarding is always disabled regardless of this value.
```

^ copied from their docs

**Comment by 4t145** [comment]
I found a hacky way to do this on windows by using [windows](https://github.com/microsoft/windows-rs) crate 
in `cargo.tmol`
```toml
[dependencies.windows]
version = "0.36.1"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
]
```
after built a tranparent and topmost window: 
```rust
let hwnd = window.hwnd().unwrap().0;
let hwnd = windows::Win32::Foundation::HWND(hwnd);
unsafe {
    use windows::Win32::UI::WindowsAndMessaging::*;
    let nindex = GWL_EXSTYLE;
    let style = WS_EX_APPWINDOW| WS_EX_COMPOSITED | WS_EX_LAYERED | WS_EX_TRANSPARENT | WS_EX_TOPMOST;
    let _pre_val = SetWindowLongA(hwnd, nindex, style.0 as i32);
};
```
It does work!

references: 
1. https://stackoverflow.com/questions/31313624/click-through-transparent-window-no-dragging-allowed-c
2. https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlonga
3. https://docs.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles

**Comment by NicolaSpadari** [comment]
> I found a hacky way to do this on windows by using [windows](https://github.com/microsoft/windows-rs) crate in `cargo.tmol`
> 
> ```toml
> [dependencies.windows]
> version = "0.36.1"
> features = [
>     "Win32_Foundation",
>     "Win32_UI_WindowsAndMessaging",
> ]
> ```
> 
> after built a tranparent and topmost window:
> 
> ```rust
> let hwnd = window.hwnd().unwrap().0;
> let hwnd = windows::Win32::Foundation::HWND(hwnd);
> unsafe {
>     use windows::Win32::UI::WindowsAndMessaging::*;
>     let nindex = GWL_EXSTYLE;
>     let style = WS_EX_APPWINDOW| WS_EX_COMPOSITED | WS_EX_LAYERED | WS_EX_TRANSPARENT | WS_EX_TOPMOST;
>     let _pre_val = SetWindowLongA(hwnd, nindex, style.0 as i32);
> };
> ```
> 
> It does work!
> 
> references:
> 
> 1. https://stackoverflow.com/questions/31313624/click-through-transparent-window-no-dragging-allowed-c
> 2. https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlonga
> 3. https://docs.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles

Can you create a minimal repo with this working?

**Comment by slauko** [comment]
^interested to see a basic working example too :) @4t145

**Comment by 4t145** [comment]
@NicolaSpadari @slauko 
check this repo https://github.com/4t145/tauri-windows-clickthrough-example

**Comment by NicolaSpadari** [comment]
I think the repo is private

**Comment by 4t145** [comment]
> I think the repo is private

oh I'm sorry about that, it's public now.

**Comment by Itokoyamato** [comment]
In case anyone needs it, it seems easier to do on macos

You need the cocoa & objc crates then you can access the NSWindow via the webview

```rust
let main_window = app.get_window("main").unwrap();
main_window.with_webview( | webview | {
  #[cfg(target_os = "macos")]
  unsafe {
    let () = msg_send![webview.ns_window(), setIgnoresMouseEvents: true];
  }
});
```

Full example:
```rust
#[cfg(target_os = "macos")]
#[macro_use]
extern crate objc;

use tauri::{WindowBuilder, Window, Manager};

fn main() {
  tauri::Builder::default()
  .setup(|app| {
    let main_window = app.get_window("main").unwrap();
    main_window.with_webview(|webview| {
      #[cfg(target_os = "macos")]
      unsafe {
        let () = msg_send![webview.ns_window(), setIgnoresMouseEvents: true];
      }
    });
    Ok(())
  })
  .run(tauri::generate_context!())
  .expect("error while running tauri application");
}
```
