### ISSUE TITLE
feat: add `window.set_visible_on_all_workspaces()`

### ISSUE THREAD

**Issue by srsholmes** [tauri-apps/tao#185]
As discussed [here](https://github.com/tauri-apps/tauri/issues/2258). 

It would be great to have the ability to have some sort of API, possibly `window.set_visible_on_all_workspaces()` to allow apps made with tao the ability to be shown on all spaces, regardless of what space they were created on. 

I have achieved this in a local copy of tao by adding the following in `src/platform_impl/macos/window.rs` line 195.

```
      ns_window.setCollectionBehavior_(NSWindowCollectionBehavior::NSWindowCollectionBehaviorCanJoinAllSpaces);
      ns_window.setCollectionBehavior_(NSWindowCollectionBehavior::NSWindowCollectionBehaviorMoveToActiveSpace);
       // TODO: get a real level?
      ns_window.setLevel_(10000);
```

I hope that helps. Please let me know if you need a hand implementing or testing.

**Comment by amrbashir** [comment]
For reference: https://www.electronjs.org/docs/api/browser-window#winsetvisibleonallworkspacesvisible-options

On windows, It is ignored.
On Linux, we call `gtk::Window::stick()
On MacOs, check the issue body.

**Comment by nksaraf** [comment]
This would be awesome to have!! Just wanted to indicate that this would be a very interesting use case

**Comment by Sneaken** [comment]
emmm.... where is src/platform_impl/macos/window.rs

**Comment by Y80** [comment]
Hello！@amrbashir @srsholmes
I want to know, why is this method not exported in tauri:: window::Window? Do I have another way to use this method in the Tauri Project?
