### ISSUE TITLE
feat: add `monitor::cursor_position()`

### ISSUE THREAD

**Issue by srsholmes** [tauri-apps/tao#186]
Adding a method called `monitor::cursor_position()` would allow us to track where the mouse cursor is on multiple desktop monitors, which would allow use to place windows where the mouse cursor lies, for example with a spotlight style app. 

This was first discussed and referenced in [this thread.](https://github.com/tauri-apps/tauri/issues/2258)

**Comment by adlrwbr** [comment]
Bump. I'd love to see this feature in Tauri!

**Comment by fakecore** [comment]
Does this feature still in development? Any substantial progress?

**Comment by FabianLars** [comment]
It wasn't ever _in development_ and at this point i'm not sure if we'll start working on it before the winit migration.

p.s. we always appreciate PRs :)

**Comment by fakecore** [comment]
ok. I would try it.

**Comment by brettinternet** [comment]
[Description of possible bug moved to #707]

**Comment by amrbashir** [comment]
@brettinternet thanks for the report, please open an issue for this
