### ISSUE TITLE
Change macOS Full Screen to Auto-Hide the Menu Bar

### ISSUE THREAD

**Issue by arpan-dhatt** [tauri-apps/tao#188]
Pressing the green button on the macOS window decorator Full Screens the window, but the Menu Bar will not show if the user moves their mouse to the top of the screen. This is different than nearly all native apps and is not the same as Electron's default behavior. This is a bigger issue when a user Full Screens an app without a custom window titlebar since the user will not be able to Close, un-Full Screen the app, or use any Menu Bar tools (like seeing the time) unless they switch out of the application.

There is also currently no configurability due to `winit`'s and and `tao`'s architecture. The relevant code and explanation is [here](https://github.com/tauri-apps/tao/blob/b42db6474a6871114a34792bf95119bdb482edfa/src/platform_impl/macos/window_delegate.rs#L485). This is also currently an [issue with `winit`](https://github.com/rust-windowing/winit/issues/1195).

I propose the output of `window_will_use_fullscreen_presentation_options` be changed from:
```rust
(NSApplicationPresentationOptions::NSApplicationPresentationFullScreen
| NSApplicationPresentationOptions::NSApplicationPresentationHideDock
| NSApplicationPresentationOptions::NSApplicationPresentationHideMenuBar)
```
to
```rust
(NSApplicationPresentationOptions::NSApplicationPresentationFullScreen
| NSApplicationPresentationOptions::NSApplicationPresentationAutoHideDock
| NSApplicationPresentationOptions::NSApplicationPresentationAutoHideMenuBar)
```
The relevant `NSApplicationPresentationOptions` docs from Apple are [here](https://developer.apple.com/documentation/appkit/nsapplicationpresentationoptions)

This will make the behavior more consistent with most applications, *except games*. This will be a **breaking change** since some apps may expect there to be no menu bar when the user hovers to the top of the screen, and there will be no configurability available to them, as there is none available to people who currently need the opposite behavior.

**Comment by amrbashir** [comment]
fixed in the next branch, will be available in the next release.
