### ISSUE TITLE
How to hide and maximize when creating and maximize immediately when displaying?

### ISSUE THREAD

**Issue by imxood** [tauri-apps/tao#193]
Below is to hide by default when creating, but not maximize when displaying
because in src\platform_impl\windows\window.rs:950, the `set_maximized ` does not work when `winuser::IsWindowVisible(window)`

![image](https://user-images.githubusercontent.com/14890680/129689023-ab966b01-389c-4469-ab38-2f89618e6e5a.png)
![image](https://user-images.githubusercontent.com/14890680/129689164-24bb30fd-0734-4459-81d7-7a2bebeabd67.png)

I can do:
```rust
hello_window.show().unwrap();
hello_window.maximize().unwrap();
```
but, sometimes the effect is not good, size change (default size -> maximize size) will cause flicker

**Comment by amrbashir** [comment]
@wusyong electron doesn't provide an option `maximized` on their `BrowserWindow` object and they said in their docs that `maximize()` will show the window.

I think there is no way to maximize the window without showing it, at least on windows.

should we remove the maximized option in the builder and only provide `set_maximized()` and document that it will show the window ?

**Comment by wusyong** [comment]
`with_maximized` is still useful for those who want to build it directly.
And `set_maximized` will still show the flicker as the author said.

We could change the behavior to prioritize maximized I suppose.
And we should document the behavior either way.
We will also need to test how to make flicker side effects disappear.
