### ISSUE TITLE
set_size adds extra pixels on on undecorated windows or windows without a menu.

### ISSUE THREAD

**Issue by FabianLars** [tauri-apps/tao#194]
edit: ahh, i was supposed to open this at tao, urgh... ~~But i guess it kinda makes sense to start here, but maybe that's just me~~

### **Describe the bug**
Please see this discord message and those below: https://discord.com/channels/616186924390023171/625037620996734986/876967731130421248

Bug seems to be windows only.

The sizes are correct until here: https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/windows/util.rs#L101
The function itself gets the correct values (x,y), but outer_y calculated with the value from adjust_window_rect is higher than expected.

With `"decorations": true` it adds 20px to the specified height.
With `"decorations": false` it adds _something_ to both the height and the width.

## To reproduce
~~I wasn't able to reproduce this in tao's examples, didn't try wry (yet?)~~.
edit: reproducable in wry,
edit2: it actually is reproducable in tao, no idea why it didn't work on my first try 🤷 

The tao one should basically be enough, but i could reproduce the behavior only with disabled decorations. On tauri and wry it's enough to not have a menu (but decorations enabled).

### in tauri
1. tauri's api example
2. in fn `main()` comment out `.menu()`
3. Replace Welcome.svelte with this:
```js
<script>
  import { getCurrent, PhysicalSize } from '@tauri-apps/api/window'

  async function resize() {
    const window = getCurrent();
    const size = await window.innerSize();
    await window.setSize(new PhysicalSize(size.width, size.height));
  }
</script>
<p on:mouseenter={resize}>
  Tauri's API capabilities using the ` @tauri-apps/api ` package. It's used as
  the main validation app, serving as the testbed of our development process. In
  the future, this app will be used on Tauri's integration tests.
</p>
```
4. hover a couple of times over the p element, the window height should increase everytime.  

### in wry
for example in custom_titlebar.rs, add the following to the WindowEvent match and focus/unfocus the window a few times.
```rs
WindowEvent::Focused(_) => {
    let w = webviews[&window_id].window();
    w.set_inner_size(w.inner_size());
}
```
p.s. don't get tricked by the visuals if you remove the `Resized` match arm for testing. The window size still increases (visible if you log `outer_x` in tao for example)

### in tao
replace (or create) an example with something like this:
```rs
use tao::{
  event::{Event, WindowEvent},
  event_loop::{ControlFlow, EventLoop},
  window::Window,
};

fn main() {
  let event_loop = EventLoop::new();

  let window = Window::new(&event_loop).unwrap();
  window.set_decorations(false);

  event_loop.run(move |event, _, control_flow| {
    *control_flow = ControlFlow::Wait;

    match event {
      Event::WindowEvent { event, .. } => match event {
        WindowEvent::CloseRequested => *control_flow = ControlFlow::Exit,
        WindowEvent::Focused(_) => window.set_inner_size(window.inner_size()),
        _ => (),
      },
      _ => (),
    }
  });
}
```

### update
https://github.com/tauri-apps/wry/commit/6eb10d4e10ce86c8403c80fb41ba5e37072dc61e seems to be the first commit where you can observe this behavior. That doesn't make much sense to me tho, as this commit with wry 0.11 and tao 0.4 was part of beta.5. (the issue is gone if you downgrade tauri to beta.5 in a project)

### update 30 or something, i lost count
The first commit that shows this behavior is this one, at least if i didn't trick myself lol: https://github.com/tauri-apps/tao/commit/f35dd03dc6f15d51fb348c6b404c195ba2401339, i wasn't able to figure out which change exactly breaks it, because i wasn't able to fix it by reverting the changes one by one (isolated)...
and i don't get how that commit can be the first one to have this bug, because that commit was part of tauri's beta.5 and it worked fine there. i think i'm loosing my mind 🤔 

### update 24.09
with wravery's PR merged into tauri, the behavior with menus changed (in tauri). Now, without a menu it works as expected, with a menu the window shrinks instead!
Undecorated windows seem to be behave the same way as before.
tbh I don't get why/how that change happened at all, because all of the code related to this seems to be unchanged as far as i can see.

**Comment by amrbashir** [comment]
I have been trying to figure this out for quite some times but I am unable to find a solution so I marked this for external help and hopefully someone can fix it. 

An obvious workaround is to just skip calling [`AdjustWindowRectEx`](https://github.com/tauri-apps/tao/blob/9da2f1592dd32000e2612a688385c3141dce01ff/src/platform_impl/windows/util.rs#L103) and pass desired width and height to `SetWindowPos` which should work as expected in most cases but that won't account for dpi at all.

**Comment by jblume** [comment]
I think for undecorated windows, the problem lies here:
https://github.com/tauri-apps/tao/blob/fb2fdf83276f05c8499bd3d79bb6d4199e6abe7c/src/platform_impl/windows/window_state.rs#L195-L206
When WS_SYSMENU, WS_CAPTION or WS_MINIMIZEBOX are set, AdjustWindowRectEx assumes the presence of the title bar and adds pixels. It's a bit weird that not setting WS_EX_WINDOWEDGE causes it not to appear.

I encountered this bug while developing a Tauri application with undecorated windows, and pulling WS_SYSMENU | WS_CAPTION | WS_MINIMIZEBOX into the branch for WindowFlags::DECORATIONS fixed it for me. I don't know about the problem with menus, though.

WS_BORDER is contained in WS_CAPTION, by the way. The line setting it is a no-op at the moment.

**Comment by amrbashir** [comment]
> I think for undecorated windows, the problem lies here:
> https://github.com/tauri-apps/tao/blob/fb2fdf83276f05c8499bd3d79bb6d4199e6abe7c/src/platform_impl/windows/window_state.rs#L195-L206
> When WS_SYSMENU, WS_CAPTION or WS_MINIMIZEBOX are set, AdjustWindowRectEx assumes the presence of the title bar and adds pixels. It's a bit weird that not setting WS_EX_WINDOWEDGE causes it not to appear.
> 

This really valuable info.

Last time I tried to fix this bug (which I forgot to comment here), I did try to account for the hidden titlebar size which kinda worked for vertical size changes but not horizontal.

I will take another attempt at it in a couple of days.

**Comment by FabianLars** [comment]
Okay sooo, funny story. It seems to have fixed itself for decorated windows with no menus again.

What i wasn't able to fix is the behavior for undecorated windows with the solution that you described or any other "solution" i found.
Since winit merged their windows-rs PR i also looked through their code but no matter what i adapted it either changed nothing, or it "fixed" it but added a weird titlebar (although it was still explicitly disabled).

**Comment by amrbashir** [comment]
> Since winit merged their windows-rs PR i also looked through their code but no matter what i adapted it either changed nothing, or it "fixed" it but added a weird titlebar (although it was still explicitly disabled).

It is not an issue with the win32 apis rust 
binding, winapi or windows-rs behaves the same. And `winit@master` have different way of removing decorations than our current imolementation.

The issue is that undecorated windows have `WS_CAPTION`, `WS_THICKFRAME`, `WS_BORDER` window styles. These styles are basically titlebar ans some borders but are hidden but `AdjustWindowRect` doesn't know that and returns a window size that accounts for them, hence the bigger size than desired.

One way to fix this issue is to detect if the window is undecorated, and remove these styles before passing them to `AdjustWindowRect` but I haven't tried this solution yet.

**Comment by FabianLars** [comment]
> It is not an issue with the win32 apis rust
> binding, winapi or windows-rs behaves the same.

Yeah i know that. What i meant is that their PR made comparing winit with tao way easier. Not easy enough tho since i didn't figure out why exactly it works in winit while it doesn't work in tao.

> And winit@master have different way of removing decorations than our current implementation.

Yeah that was what i meant with my last sentence, I tried adapting their way for that (and other stuff) in tao, but that didn't go well, which ofc means that i just missed something obvious again.

> The issue is that undecorated windows have WS_CAPTION, WS_THICKFRAME, WS_BORDER window styles.

Yeah ik, maybe i misunderstood what they meant with "and pulling [...] into the branch for `WindowFlags::DECORATIONS` fixed it for me" 🤷 

> One way to fix this issue is to detect if the window is undecorated, and remove these styles before passing them to AdjustWindowRect but I haven't tried this solution yet.

Yeah that works (tested it), but imo it looks/feels really weird or hacky or whatever, but better than nothing lol

But anyway, the initial purpose of my "experiment" was to test _decorated_ windows again, and yeah, that somehow fixed itself 🤷 i didn't find _any_ related changes since i created the issue that could have fixed this btw and it seems like "downgrading" doesn't make the issue re-appear either. i'm just happy that i asked others to test it too back then, otherwise i'd think i'd be crazy.

**Comment by amrbashir** [comment]
> Yeah that works (tested it), but imo it looks/feels really weird or hacky or whatever, but better than nothing

It is not hacky, it is the only way that makes sense and actually microsoft has a [guide](https://docs.microsoft.com/en-us/windows/win32/dwm/customframe#appendix-c-hittestnca-function) that does that for hit testing. Anyways, I am glad it worked, I will add it on top of my todo list, and will try to finalize it when I get back.
