### ISSUE TITLE
refactor: Icons

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/tao#204]
As Windows menu now support icons, It’s the right time to start working on a refactor for all the icons required in `tao`.

The main objective is to align all icons (tray, menu, window)  to use our [`Icon`](https://github.com/tauri-apps/tao/blob/dev/src/icon.rs) struct for all platforms.

We need to think how we can align system tray icons linux (path and vector of bytes)

**Comment by lemarier** [comment]
We also need to think how we can make the tauri life easier.

Moving tauri away from the JS api (icons) , will really help. 
Did we need to make any changes in `tao`?

**Comment by amrbashir** [comment]
I forgot about this issue, but #328 took care of this
