### ISSUE TITLE
Accelerator support for virtual keys like `+`

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tao#227]
A common keyboard shortcut is `CmdOrCtrl+Plus`, which tao currently doesn't support (at least on macOS, not sure about other platforms)

Returning `"+"` from `Accelerator::key_equivalent` on macOS and it gave me `⌘+` in the menu bar. On my keyboard, both `⌘=` and `⌘⇧+` trigger that shortcut (which is expected).

**Comment by probablykasper** [comment]
In browser keyboard events, it works like this
- `=` -> `{ e.key: "=", e.code: "Equal" }`
- `⇧=` -> `{ e.key: "+", e.code: "Equal" }`

**Comment by amrbashir** [comment]
> A common keyboard shortcut is `CmdOrCtrl+Plus`, which tao currently doesn't support (at least on macOS, not sure about other platforms)

Can't you just use `CmdOrCtrl+Shift+=`?

**Comment by probablykasper** [comment]
> Can't you just use `CmdOrCtrl+Shift+=`?

Not if you want to match the behavior of Safari, TextEdit etc. On my Norwegian keyboard, `+` and `=` are on different keys.

**Comment by amrbashir** [comment]
Ah I see, We need to discuss this as it might require a lot of changes to make it consistent for all platforms. cc @lemarier @wusyong
