### ISSUE TITLE
update windows.rs

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tao#239]
Might be time, we are pretty far behind (latest is `0.25.0` and we are on `0.19.0`.

**Comment by amrbashir** [comment]
As of `0.23.0`, `windows-rs` includes pre-packaged apis (like `winapi` crate).

We need to wait until `webview2-rs`  also updates its version so we don't build two different versions of `windows-rs` in our stack and increase build time.

**Comment by nothingismagick** [comment]
See this:

https://github.com/microsoft/windows-rs/issues/1285#issuecomment-963560540

**Comment by amrbashir** [comment]
cool, wasn't aware that wravery already updated the webview crate.
