### ISSUE TITLE
`Tab` accelerator not working on Linux

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tao#242]
Not sure if it's just happening for me, but `Tab` does not seem to work for menu bar accelerators on Linux. The shortcut shows up correctly as `Tab` in the menu, but doesn't trigger when I press `Tab`.

Judging by the source code, it looks like `Tab` should work.

I'm running Ubuntu 20.04.

**Comment by amrbashir** [comment]
related discussion https://github.com/Guake/guake/issues/152

**Comment by amrbashir** [comment]
and the solution https://github.com/Guake/guake/issues/152 , I probably won't work to fix this anytime soon though.

**Comment by amrbashir** [comment]
Guake solved this in https://github.com/Guake/guake/pull/1902 by keeping a map of keybindings (aka accelerators) and their action, then listened to `key-press` event on the window and if it matched one of the keybindings, they manually execute the associated action. This is manual and I think they don't even rely on gtk menu accelerators at all. 

I don't think we can do much here but tao users can listen to `tao::WindowEvent::Key` and execute their action if it matched their `Tab` accelerator.
