### ISSUE TITLE
Status bar use `Vec<u8>` for icon instead of path

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/tao#25]
We should use vec<u8> as the icon in the statusbarbuilder will be handled by tauri and the icon is bundled in source, not available as a path

**Comment by wusyong** [comment]
I changed it because it's the only way to do on Linux
https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/linux/status_bar.rs#L25
And it doesn't seem to have option to use Vec<u8>
https://docs.rs/libappindicator/0.5.2/libappindicator/struct.AppIndicator.html

**Comment by lemarier** [comment]
because in tauri, the icon is burned in the binary, so the path isnt available. Any idea of what we could do?

Edit: Maybe write the vec to a tmpfile :/ ?

**Comment by wusyong** [comment]
I'm looking [tempfile](https://docs.rs/tempfile/3.2.0/tempfile/) to use on Linux.

**Comment by lemarier** [comment]
Reminder to @wusyong so he can make sure everything is correct internally

https://github.com/tauri-apps/tao/pull/27#issuecomment-834616258
