### ISSUE TITLE
feat: `window.is_minimized()`

### ISSUE THREAD

**Issue by amrbashir** [tauri-apps/tao#257]

**Comment by PerBothner** [comment]
Example use-case: A `toggle-minimize` command bound to a key that displays or minimizes a window. For example a popup terminal or "quake mode" terminal. This requires is robust method to tell if a window is already minimized, or a reliable event notification if (for example) the uses clicks a minimize button is a system titlebar.

**Comment by PerBothner** [comment]
A related issue: The documentation for `is_visible` doesn't state whether a minimized window is considered visible or not. I think it should. I haven't yet tested what the implementation does - it may depend on the platform.

**Comment by amrbashir** [comment]
yeah IIRC, macOS is differential than other platforms and we should document that.
