### ISSUE TITLE
Moved event not fired correctly on Wayland

### ISSUE THREAD

**Issue by FabianLars** [tauri-apps/tao#259]
This problem can be split up into 2:
1. The Moved event doesn't get triggered when you move the window, you need to trigger another event to trigger the Moved event _once_ (there is no queue that empties once you trigger some other event, the triggered Moved events match the amount of triggers of the other event)
2. The reported position is always 0, 0

This behavior doesn't seem to be new, as it behaves the same in tauri@beta.8 (== the last release of tao), i also rolled back some commits in tao and didn't see a difference.

System is fedora 35 with gnome
Also: This works fine on X11.

## To reproduce
Imo the easiest way to do that is to add this to the resizable example (or whatever example that already has WindowEvents other than CloseRequested.
```rs
WindowEvent::Moved(position) => {
    dbg!(position);
}
```
So in the resizable example you would end up with this:
```rs
match event {
  Event::WindowEvent { event, .. } => match event {
    WindowEvent::CloseRequested => *control_flow = ControlFlow::Exit,
    WindowEvent::Moved(position) => {
      dbg!(position);
    }
    WindowEvent::KeyboardInput {
      event:
        KeyEvent {
          physical_key: KeyCode::Space,
          state: ElementState::Released,
          ..
        },
      ..
    } => {
      resizable = !resizable;
      println!("Resizable: {}", resizable);
      window.set_resizable(resizable);
    }
    _ => (),
  },
  _ => (),
};
```

Edit: just a small heads up, because i just trolled myself. To properly test this, the cargo run command must be executed from a wayland context like a native terminal. vscode's built-in terminal for example won't work, because it uses XWayland!

**Comment by i509VCB** [comment]
Per the gtk docs: https://docs.gtk.org/gtk3/method.Window.get_position.html

> The reliability of this function depends on the windowing system currently in use. Some windowing systems, such as Wayland, do not support a global coordinate system, and thus the position of the window will always be (0, 0)

**Comment by FabianLars** [comment]
Ahh fun stuff. Thanks for the info!
Sooo, we should add this to our docs too then. (I mean, we _could_ force the x11 backend, but yeah, let's not do that lol)
