### ISSUE TITLE
[feat] Support child windows on Linux

### ISSUE THREAD

**Issue by vdvman1** [tauri-apps/tao#273]
Child windows are currently supported on [windows](https://github.com/tauri-apps/tao/blob/f8866a084afe18983c91c67401d8759697578a9c/src/platform/windows.rs#L171) and [mac](https://github.com/tauri-apps/tao/blob/f8866a084afe18983c91c67401d8759697578a9c/src/platform/macos.rs#L308) under the platform specific window APIs, however there does not appear to be an equivalent API for linux.
According to Amr Bashir on discord, child windows are possible on linux, so creating an API in tao for linux would then make it possible to have child windows on all supported platforms.

I am not sure if a common API would be a good idea or not, since child windows apparently behave differently on different platforms, but it may be good to have and to just document the differing behaviour.

**Comment by keiya01** [comment]
Can we use [Window.set_transient_for](https://docs.gtk.org/gtk3/method.Window.set_transient_for.html) for child window?
