### ISSUE TITLE
how to add input at title

### ISSUE THREAD

**Issue by bingryan** [tauri-apps/tao#284]
![image](https://user-images.githubusercontent.com/41174435/149630334-df527c50-27a3-4725-9bd7-096bb5d8dbc5.png)

**Comment by amrbashir** [comment]
are you using tauri? or doing native macOS gui?

**Comment by bingryan** [comment]
> are you using tauri? or doing native macOS gui?

https://github.com/tauri-apps/tao/blob/next/examples/custom_menu.rs

**Comment by bingryan** [comment]
yes,but i just run tao example: custom_menu.rs

**Comment by amrbashir** [comment]
Adding an input to the titlebar is out of this project scope but I just wanted to know whether you are using tauri or doing native macOS gui so I can help you move in the right direction.

You need to disable decorations, then make a custom titlebar and make the input as you like in HTML/CSS/JS.
