### ISSUE TITLE
[Question] How to get opengl context?

### ISSUE THREAD

**Issue by dinfer** [tauri-apps/tao#322]
Is there a way to get opengl context ? The official winit and glutin cannot be compiled to android. [mr](https://github.com/rust-windowing/glutin/pull/1385) .

**Comment by amrbashir** [comment]
tao is basically winit with a different linux backend, if winit won't work on android, tao won't

**Comment by amrbashir** [comment]
And getting the opengl context is not different than how you get it in winit (well, except on Linux).

**Comment by dinfer** [comment]
OK, I'm using glutin to access OpenGL, and glutin is using winit. Is there a suggested method to get OpenGL context using tao?

**Comment by amrbashir** [comment]
here is a [glutin](https://github.com/wusyong/glutin) fork by @wusyong that works with tao.
