### ISSUE TITLE
winit differences?

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tao#325]
In how far is `tao` different than `winit`? What were the reasons for starting this project / requirements to be met?

**Comment by wusyong** [comment]
See [this comment](https://matrix.to/#/!DGpLzJTRzBDTwZiogk:matrix.org/$NB-WvUAJOtCzgEbCmQ-tKTM5WQFDaybK7-jJrw3IPzM?via=libera.chat&via=matrix.org&via=sandbox.hackerfoo.com) in winit's matrix.
I'll add this in readme to clarify this. In the near future, I hope we can make the features we need into several crates and become more modular. So winit can also benefit from it.
