### ISSUE TITLE
enhancement: relaxed shortcut key support

### ISSUE THREAD

**Issue by RyKilleen** [tauri-apps/tao#342]
Currently the accelerator doesn't accept more than one main key:

https://github.com/tauri-apps/tao/blob/dev/src/accelerator.rs#L281

I'm curious what the reasoning is behind this? As a user of the type of app I'm building, I'd love to be able to assign more than one main key to my shortcut.

**Comment by amrbashir** [comment]
What is the key combination you'd want to use? I never saw an app with more than one main key so I am a bit curious.

**Comment by RyKilleen** [comment]
In this instance, it's a omnibar task-runner type app and I'd love to leave it fully up to the user. I know some folks like to keep it simple, and some people have a lot of bindings they're trying to work around.

Something like `ctrl + space + x` or `alt + space + a`  or `shift+alt+space` doesn't seem unreasonable for a keyboard shortcut.  Mostly I was curious if it's an arbitrary rule or if there are real ramifications to it.

**Comment by amrbashir** [comment]
You can have multiple modifiers (`Shift`, `Alt`, `Ctrl`) but only one main Key is supported. 
- `ctrl+space+x` is **not** supported.
- `alt+space+a` is **not** supported.
- `shift+alt+space` is **supported**.

Doing multiple keys is really unusual. For instance, VSCode requires you to press a sequence for shortcuts. For example, if you have `ctrl+space+x` shortcut, users need to press `Ctrl+Space` then `Ctrl+X` within a short period of time.

**Comment by RyKilleen** [comment]
I can recreate the described functionality in several of the task launchers I'm using as inspiration. Would you say this is a stylistic choice, not a technical limitation?

**Comment by amrbashir** [comment]
Our current implementation of `GlobalShortcuts` (Which might be removed soon btw) has a limitation on Windows, that it can have multiple modifiers but only one main key. See https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey

The plan is to remove `GlobalShortcut` module and users of `tao` will build their own global shortcut manager on top of `DeviceEvent::Key`

**Comment by RyKilleen** [comment]
Totally understand and appreciate the head's up on the deprecation, thanks!
