### ISSUE TITLE
Set `CRATE_TOKEN` in Github secrets

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/tao#35]
- [x] License headers
- [x] Authors field and package meta
- [x] Align Readme with tauri (description) and badges
- [x] Library description (github)
- [x] Library documentation quick review
- [x] Delete existing tags on current repo to prevent any issues

**Comment by lemarier** [comment]
I'll reopen because we need to have the `CRATE_TOKEN` in place for crates.io release in our Github secret for the Github Actions.

**Comment by nothingismagick** [comment]
Token added
