### ISSUE TITLE
Cursor flickering when hovering on the border of frameless window

### ISSUE THREAD

**Issue by idlist** [tauri-apps/tao#386]
Firstly mentioned in [tauri#3040](https://github.com/tauri-apps/tauri/issues/3040) and also in #376.

That is to say, when hover the cursor **inside the dragging room of resizing operation** on the border of a frameless window, the cursor would quickly flicker between "default" and "two-sided arrow", and making it somewhat hard to identify if I can resize the window with current cursor position (since sometimes the cursor would be "default" when I stop moving it inside the dragging room). This behavior is more obvious on screen with high DPI scaling factor.

This GIF shows the flickering when moving the cursor outside of the window (the window is on the left of the CSS border line). The behavior could be also observed when moving cursor into the window.
![flickering1](https://user-images.githubusercontent.com/29368226/167255349-5935e0a5-48c0-4a58-b473-37b461d6a3b0.gif)

This GIF shows the possible confusion brought by the issue. In this case, the cursor shows "default" inside the dragging room instead of "two-sided arrows", and when I click on the position (yellow circle indicates when I click) I can actually drag the border but I may treat it as I cannot.
![flickering2](https://user-images.githubusercontent.com/29368226/167255436-0af38b2c-7bad-42c3-baf2-156be5e07b99.gif)

**Comment by amrbashir** [comment]
Closing as I don't think there is much we can do to fix this. We are achieving the resizability for undecorated windows by responding to the win32 window message [`WM_NCHITTEST`](https://learn.microsoft.com/en-us/windows/win32/inputdev/wm-nchittest) on `tao` and emulating it in `wry` by synthesizing the same win32 window message in reaction to `mousedown` and `mousemove` JS events
