### ISSUE TITLE
Adding README.md to src/examples 

### ISSUE THREAD

**Issue by khuongduy354** [tauri-apps/tao#394]
I just want to add a small README file like 

https://github.com/tauri-apps/wry/tree/dev/examples#readme 

to be more descriptive about the examples.

**Comment by nothingismagick** [comment]
great idea!

**Comment by khuongduy354** [comment]
#398 
This is my first pull request ever, I'm not a native English but I hope the doc I add is understandable, correct me if I'm wrong.

**Comment by wusyong** [comment]
Closed by #398
