### ISSUE TITLE
I want to know  what the tauri and tao and flutter;

### ISSUE THREAD

**Issue by shijianzhong** [tauri-apps/tao#403]
I have something not understand

I want to know  what the relation about  tauri and tao and flutter;

The tauri how to support mobile app；

I know the tao depends on the winit，and the winit depends on the native  like  the flutter;

But the tauri depends on the webview, play with js,css,html;

So I want to know the tauri. How to support the mobile app ??? Also webview???

**Comment by amrbashir** [comment]
You can read about our architecture here https://tauri.studio/about/architecture . If you have more questions please ask on our discord.
