### ISSUE TITLE
bug(macos):  Unable to move background with `with_movable_by_window_background`

### ISSUE THREAD

**Issue by jkelleyrtp** [tauri-apps/tao#406]
https://github.com/atom/atom/pull/10208

There's a bunch of history regarding this one in the Electron world on how to "hide decorations but keep the traffic lights around."

I think a slight tweak in the flags would allow two types of decorations (title bar, and the traffic lights).

**Comment by lemarier** [comment]
https://www.electronjs.org/docs/api/frameless-window#hidden

**Comment by lemarier** [comment]
Sorry I totally forgot!

We already support it!

This is an example;
```rust
use simple_logger::SimpleLogger;
use tao::{
  event::{Event, WindowEvent},
  event_loop::{ControlFlow, EventLoop},
  window::WindowBuilder,
};

#[cfg(target_os = "macos")]
use tao::platform::macos::WindowBuilderExtMacOS;

#[allow(clippy::single_match)]
fn main() {
  SimpleLogger::new().init().unwrap();
  let event_loop = EventLoop::new();

  let mut window_builder = WindowBuilder::new()
    .with_transparent(true)
    .with_title("My window");

  #[cfg(target_os = "macos")]
  {
    window_builder = window_builder.with_titlebar_transparent(true);
  }

  #[cfg(not(target_os = "macos"))]
  {
    window_builder = window_builder.with_decorations(false);
  }

  let _window = window_builder.build(&event_loop).unwrap();

  event_loop.run(move |event, _, control_flow| {
    *control_flow = ControlFlow::Wait;
    match event {
      Event::WindowEvent {
        event: WindowEvent::CloseRequested,
        ..
      } => *control_flow = ControlFlow::Exit,
      _ => (),
    }
  });
}
```

Results;

![Screen Shot 2021-07-15 at 1 32 52 PM](https://user-images.githubusercontent.com/22237916/125831833-0499544a-2440-4fcb-8cc7-e8254060c3d9.png)

**Comment by lemarier** [comment]
PS; more details can be found here;

https://docs.rs/tao/0.4.0/x86_64-apple-darwin/tao/platform/macos/trait.WindowBuilderExtMacOS.html#tymethod.with_titlebar_transparent

**Comment by jkelleyrtp** [comment]
Hmm, I'm sure some combination works but I can't figure it out.

With:
- transparent
- title
- titlebar_transparent

It works, kinda, but the titlebar is literally transparent, meaning I can see content behind it. The ideal layout here being a transparent titlebar that sits on top of the content, not above it. Am I missing something?

Also thanks for taking a look so quickly.


![Screen Shot 2021-07-15 at 1 50 10 PM](https://user-images.githubusercontent.com/10237910/125834054-dba10e90-31d5-45a6-a634-4014ef3c2862.png)


```
        c.with_transparent(true)
            .with_title("Example Website")
            .with_titlebar_transparent(true)
```

## update

with 
```rust
        c.with_transparent(true)
            .with_title("Example Website")
            .with_movable_by_window_background(true)
            .with_fullsize_content_view(true)
            .with_titlebar_buttons_hidden(false)
            .with_titlebar_transparent(true)
```
I get the right appearance, but I can't seem to drag the window around at all.

**Comment by lemarier** [comment]
Ok, I've made some tests, and looks like the tao window is working fine without the webview.

I'll transfer this issue over wry. I'll keep doing some research and update the issue as it'll go.

Thanks for reporting.

**Comment by keiya01** [comment]
Do we need to propagate drag and drop event from wkwebview to nswindow like https://stackoverflow.com/a/54987061 ?

**Comment by wusyong** [comment]
@keiya01 worth giving it a try I guess. I'm not fond of additional drop handler either.

**Comment by schickling** [comment]
Yay for closing this one! 🙌 

Will this be part of Tauri 1.0?

**Comment by FabianLars** [comment]
As far as I can see Yes. depending on how we release tao it will be part of the current tauri version too (via `cargo update`).

**Comment by mihirsamdarshi** [comment]
Is there a method for not making the _entire_ window movable, but retaining the movable title bar when the title bar is hidden? For example, the behavior exhibited by VSCode or Zoom on macOS?

**Comment by jkelleyrtp** [comment]
> Is there a method for not making the _entire_ window movable, but retaining the movable title bar when the title bar is hidden? For example, the behavior exhibited by VSCode or Zoom on macOS?

You want to disable move and then have a handler for an element that shells out to the window.drag method:

https://github.com/tauri-apps/tao/blob/dev/examples/drag_window.rs
