### ISSUE TITLE
[Documentation] Is tray available on Windows?

### ISSUE THREAD

**Issue by hybridherbst** [tauri-apps/tao#420]
I'm a bit confused by the wording in the Readme: it mentions this is a cross-platform library but goes on to state that tray is only available on Linux.

Are methods to add tray icons, explorer context items, ... part of tao and more specifically the Tauri ecosystem yet?

**Comment by amrbashir** [comment]
Trays are supported on Windows, maybe the wording on the readme needs update.

> Are methods to add tray icons, explorer context items, ... part of tao and more specifically the Tauri ecosystem yet?

Yes, in tao and tauri, you can create system tray icons(with a menu if you want) and menu bars on the window level on Windows and Linux, and menu bar for the app on macOS

**Comment by hybridherbst** [comment]
Thanks for the clarification!
Are you aware of a way to also have explorer context menu items in tauri? (usually called Shell Extensions)

**Comment by amrbashir** [comment]
you mean like `Open with <your app>`?

**Comment by hybridherbst** [comment]
That's a special case (file type registration). I'm referring to generic menus, e.g. what SharpShell does:
- https://github.com/dwmkerr/sharpshell#shell-context-menus

**Comment by amrbashir** [comment]
> That's a special case (file type registration). I'm referring to generic menus, e.g. what SharpShell does:

It is actually the same and it is not implemented yet.
On Windows, this is simple, it is just a matter of adding a registry key in the right location for your use case. You can use win32 apis through `windows-rs` crate to do this or spawn a `powershell` command to do it.

**Comment by hybridherbst** [comment]
It's not the same as far as I'm aware, these context menus are fully programmable (nested hierarchies etc.) - I'm not aware of a way to do that through the registry.

**Comment by amrbashir** [comment]
Check this SO https://stackoverflow.com/a/2069565 and the links in it. It has useful info about this. Join our discord if you want to discuss this further. This issue seems resolved to me so no need to diverge of its subject.

**Comment by hybridherbst** [comment]
Thanks, I agree this can be closed, but the SO is about a totally different topic :) (file type associations, not shell extensions)

**Comment by amrbashir** [comment]
The .NET library you mentioned above, links to this MSDN article(https://docs.microsoft.com/en-us/windows/win32/shell/context-menu-handlers?redirectedfrom=MSDN) which goes in detail on how to register shell context menus handlers through registry keys and more. 

From the article: 
> In Windows 7 and later, you should resort to COM code-based solutions only when the static methods are insufficient.

We won't implement this directly in tao or tauri but whatever you want to do can be done through `windows-rs` crate, be it COM or simple registry manipulation.

I am happy to discuss this and help as much as I can over at discord. Just ping me in the Server.
