### ISSUE TITLE
[macOs] shortcut keys for Hide Others menu is not consistency

### ISSUE THREAD

**Issue by bangnokia** [tauri-apps/tao#431]
On the macOS by default, the keyboard shortcut for the `Hide Others` menu is `option+cmd+h`.
Currently, the Tauri app is using `option+cmd+w`, which does not seem consistent with other apps.

**Comment by lucasfernog** [comment]
A good resource to check our shortcuts might be https://github.com/alacritty/alacritty/pull/4958

**Comment by keiya01** [comment]
resolved in https://github.com/tauri-apps/tao/pull/447
