### ISSUE TITLE
Termux support 

### ISSUE THREAD

**Issue by leap0x7b** [tauri-apps/tao#448]
Termux have X11 packages. Is it possible to force cargo to use the Linux target but still using the normal aarch64-linux-android target

**Comment by amrbashir** [comment]
Please ask in the termux community. Also iirc, termux only has the android targets in their package repositories, and they don't even offer rustup. Even if you downloaded rustup directly and used it to install the linux target, you will run into some weird issues so I'd recommend you ask in the termux community.
