### ISSUE TITLE
Linux window role support

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tao#455]
It would be nice to be able to set your window's role in order to differentiate between them when looking through x11 window properties. Setting wmclass would also work, but that seems to be deprecated.

Relevant docs:
[GTK Window.set_role](https://docs.gtk.org/gtk3/method.Window.set_role.html)
[GTK Window.set_wmclass](https://docs.gtk.org/gtk3/method.Window.set_wmclass.html)

**Comment by amrbashir** [comment]
`tao` exposes the `gtk::ApplicationWindow` used through https://docs.rs/tao/latest/tao/platform/unix/trait.WindowExtUnix.html#tymethod.gtk_window , then you can call `set_role` on it but you'd need to import the `gtk::GtkWindowExt` trait into scope first.

**Comment by ghost** [comment]
Ah, that works!
