### ISSUE TITLE
Xf86Paste key event not recognised/actioned

### ISSUE THREAD

**Issue by OJFord** [tauri-apps/tao#475]
In any text area or input field where I can right-click & select 'paste', the `Xf86Paste` keysym is not recognised  - or at least, no pasting happens.

I don't really know what I can provide that's of use, but happy to find any relevant logs or whatever if you can tell me.

I'm using tao 0.12.1 (via tauri 1.0.4) - and several older versions I don't have a record of, I'm not suggesting it's a regression.

**Comment by amrbashir** [comment]
can you try in epiphany browser and see if this key works? I think this might be related to webkit2gtk and thus WRY not TAO

**Comment by OJFord** [comment]
Sorry I missed this @amrbashir - just tried and indeed it doesn't work in epiphany. (v42.4, using webkit2gtk-4.1 v2.36.7 (lots of versioning going on there!))

Are you able to move this issue to tauri-apps/wry or should I reopen there?

**Comment by amrbashir** [comment]
Unfortunately it is not something that we can solve, it is an issue with webkit itself.

**Comment by OJFord** [comment]
Reported upstream: https://bugs.webkit.org/show_bug.cgi?id=245542
