### ISSUE TITLE
[feat]Customize titlebar

### ISSUE THREAD

**Issue by DreamSaddle** [tauri-apps/tao#490]
Hey guys!

Can I customize the title bar of the window? Like this, If so, how can I implement it?

![179883178-ae79dab3-9c65-42c5-b1f7-d905ead67b2a](https://user-images.githubusercontent.com/31559386/179983745-c1e7fe85-68f9-46dd-9de5-b39cfef66d2d.png)

**Comment by amrbashir** [comment]
As we use raw win32 and not UWP (specifically WinUI), this is not possible. You have to hide the decorations, and make a custom one that looks like this either through raw win32 drawing APIs or through HTML if you're using Wry or Tauri.

**Comment by DreamSaddle** [comment]
Yes, I found the answer in wry's [example](https://github.com/tauri-apps/wry/blob/d7c9097256/examples/custom_titlebar.rs). However, the operation button of the window needs to be as close to the original style as possible. I hope that `wry` official can provide a unified solution, thank you!

**Comment by amrbashir** [comment]
You need to make it yourself unfortunately, `wry` shouldn't care what you put in your HTML.
