### ISSUE TITLE
Support QT on linux

### ISSUE THREAD

**Issue by traverseda** [tauri-apps/tao#502]
GTK is not exactly a vendor neutral toolkit, it prioritizes support for Gnome above all else. One example of this is in the file selector, where they've moved the open button on the top of the toolbar, which is different from how it is on Windows, MacOs, and ever other desktop environment on linux.

Personally I find this very poor ergonomics, although I realize that opinions may vary.

QT is a solid platform and QT webengine is pleasant to work with. QT also has some nice features for working with embedded linux, which I believe would make using tauri in embedded/kiosk roles easier. It would be nice if QT was a supported toolkit on linux. I realize you already have GTK support, and that this is probably going to be a very low priority.

QT window decorations also tend to blend in with other desktop environments better than Gnome apps do.

**Comment by FabianLars** [comment]
For qtwebengine specifically, we had this issue: https://github.com/tauri-apps/tauri/issues/4554. I figure the answer here would be roughly the same.

**Comment by traverseda** [comment]
Ahh, I didn't see that. It can be hard when there are multiple repositories like this.
