### ISSUE TITLE
[bug] Window not showing on Wayland

### ISSUE THREAD

**Issue by Tim-Paik** [tauri-apps/tao#503]
Valid for all examples
tag: tao-v0.12.1 everything is normal
tag: tao-v0.13.0 window does not display, taskbar icons are created normally
Everything works fine in x11 mode (using `GDK_BACKEND=x11` environment variable)

Environment
  › OS: Arch Linux Rolling Release X64
  › DE: GNOME 42.3 + Wayland
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

**Comment by wusyong** [comment]
Does the frame of the window still show up?
Could you test if it's caused by this PR?
https://github.com/tauri-apps/tao/pull/495

**Comment by Tim-Paik** [comment]
> Does the frame of the window still show up? Could you test if it's caused by this PR? #495

The window frame is not displayed. For the latter, I think yes, b905852 can be displayed normally, but not after db7e5cb

**Comment by wusyong** [comment]
Okay I got a wayland setup and found disabling double buffer cause this.
I'll need to find out if it can be painted by GL libraries when remove that line.
But I haven't done wayland support yet.
If you are urgent, I can comment out that line first as patch.

**Comment by Tim-Paik** [comment]
It's not a big problem for me, my application is still stuck in tao 0.12.1, and I can use the x11 backend to avoid it in my development. But hopefully this issue doesn't affect tauri, which would break native Wayland support.
Thanks for your work!

**Comment by Tim-Paik** [comment]
Fixed! #504
