### ISSUE TITLE
[bug] Weird tao tray window appears when right clicking the tray icon

### ISSUE THREAD

**Issue by johnyburd** [tauri-apps/tao#506]
### Describe the bug

On windows I can put my machine into a state where right clicking the tray icon will open this weird blank window called `tao_system_tray_window`. Closing the window makes the tray icon disappear. The app and tray icon seem to functionally normally aside from the window.

![image](https://user-images.githubusercontent.com/4121471/182192425-685153b9-b6dc-4ab9-b39d-ec1c9011430b.png)

## Steps
* `yarn create tauri-app` with all default options
* add to tray icon to `tauri.conf.json`
* build system tray **with menu** in `main.rs`
* run app with `yarn tauri dev` (running a production build should work too)
* Launch slack and join a huddle
* Screenshare a webview based window in slack i.e. microsoft edge or vs code
* right click tauri tray icon
* weird window appears

## Reproduction repo
I've reproduced the issue in this repo, which I created by following the steps above.
[https://github.com/Cytracom/tao-repro-repo](https://github.com/Cytracom/tao-repro-repo)

## Notes:
* screensharing in zoom or discord doesn't seem to cause the issue.
* The issue is reproducible until I close slack even if I've stopped screensharing and left the huddle.
* Sharing edge or vscode directly trigger the issue, but sharing the whole screen does not.

### Expected behavior

No extra windows when I right click the tray icon

### Platform and versions

```
yarn run v1.22.19
warning package.json: No license field
$ tauri info

Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 103.0.1264.77
  › MSVC:
      - Visual Studio Community 2022
  › Node.js: 16.15.1
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ dist
  ├─ node_modules
  └─ src-tauri
Done in 8.74s.```

### Stack trace

_No response_

### Additional context

_No response_

**Comment by amrbashir** [comment]
Thanks for the report, I forgot to fix it in #489 too.
