### ISSUE TITLE
[bug] Keyboard shortcut alt+space does not open the window menu

### ISSUE THREAD

**Issue by marisademeglio** [tauri-apps/tao#547]
### Describe the bug

When the user presses alt+spacebar, the window menu ("Restore", "Move", "MInimize", etc) should appear but it doesn't. Right-clicking on the window title bar brings up this menu. 

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 17.2.0
  › npm: 8.1.4
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.4 (outdated, latest: 1.0.5)
  › @tauri-apps/api [NPM]: 1.0.0-rc.6 (outdated, latest: 1.0.2)
  › tauri [RUST]: 1.0.3,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../docs
  › devPath: http://localhost:5555/

App directory structure
  ├─ node_modules
  ├─ docs
  ├─ src-tauri
  └─ .git
```

**Comment by henry40408** [comment]
I have reproduced the issue on Windows 10 but not on Debian 11.

It seems macOS doesn't have such behavior. Maybe we can remove `platform: macOS`?

I'd like to take a look on this issue and try to resolve it.

## Windows

```
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 104.0.1293.63
  › MSVC:
  › Node.js: Not installed!
  › npm: Not installed!
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
```

## Linux

```
Environment
  › OS: Debian 11 X64
  › Node.js: Not installed!
  › npm: Not installed!
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
```

**Comment by amrbashir** [comment]
> It seems macOS doesn't have such behavior. Maybe we can remove platform: macOS?

the author tauri info says he is on macOS, if native macOS doesn't have the behavior then we can remove it.

**Comment by FabianLars** [comment]
Here is the relevant discord thread: <https://discord.com/channels/616186924390023171/1001148874418827314>

It indeed was about Windows all along. I asked for this issue to be created, but didn't check the tauri info output, sorryy :v:
