### ISSUE TITLE
feat: Want to create a sub window with the position relative to a parent window

### ISSUE THREAD

**Issue by Squitch1** [tauri-apps/tao#558]
Hello, I want to create a sub-window that cannot be moved by the user, and with their position is relative to other window. In fact, I want to achieve the `BrowserView` of electron: https://www.electronjs.org/fr/docs/latest/api/browser-view

**Comment by amrbashir** [comment]
We have an [API](https://docs.rs/tao/latest/x86_64-pc-windows-msvc/tao/platform/windows/trait.WindowBuilderExtWindows.html#tymethod.with_parent_window) for that on Windows but unfortunately I am not aware of similar thing on macOS/Linux

**Comment by amrbashir** [comment]
Closing since I couldn't find an useful API on platforms other than Windows.
