### ISSUE TITLE
Is there a way to implement any event handling customized by the user in tao?

### ISSUE THREAD

**Issue by imxood** [tauri-apps/tao#577]
I want to implement listening for USB device plug and unplug events, in tao,

Like this, there are other event handling that tao does not implement, Is there a way to achieve any specific event handle the user wants? 

Here is the hardcoded implementation of the code for usb plug and unplug events:
` line 1031 in src\platform_impl\windows\event_loop.rs `
```rust
win32wm::WM_DEVICECHANGE => {
      match wparam.0 as u32 {
        DBT_DEVICEARRIVAL => {
          println!("device arrival");
        }
        DBT_DEVICEREMOVECOMPLETE => {
          println!("device remove complete");
        }
        DBT_DEVNODES_CHANGED => {
          println!("dev nodes changed");
        }
        _ => {
          println!("WM_DEVICECHANGE message received, value {} unhandled", wparam.0);
        }
      }
      result = ProcResult::Value(LRESULT(0));
    }
```

Here is the code implemented by the user himself, using the windows api to register event notifications:
```rust
    let mut notify_filter = DEV_BROADCAST_DEVICEINTERFACE_W::default();
    notify_filter.dbcc_size = size_of::<DEV_BROADCAST_DEVICEINTERFACE_W>() as u32;
    notify_filter.dbcc_devicetype = DBT_DEVTYP_DEVICEINTERFACE.0;
    notify_filter.dbcc_classguid = windows::core::GUID::from_values(
      0x25dbce51,
      0x6c8f,
      0x4a72,
      [0x8a, 0x6d, 0xb5, 0x4c, 0x2b, 0x4f, 0xc8, 0x35],
    );

    unsafe {
      RegisterDeviceNotificationW(
        HANDLE(thread_msg_target.0),
        &notify_filter as *const DEV_BROADCAST_DEVICEINTERFACE_W as *const c_void,
        POWER_SETTING_REGISTER_NOTIFICATION_FLAGS(
          DEVICE_NOTIFY_WINDOW_HANDLE.0 | DEVICE_NOTIFY_ALL_INTERFACE_CLASSES,
        ),
      );
    }

    println!("RegisterDeviceNotification");
```

here is the effect:
![image](https://user-images.githubusercontent.com/14890680/193396187-5cea5096-b10c-477f-8ea4-512ecdad5fef.png)

**Comment by amrbashir** [comment]
There is no plans on directly supporting this in tao at the moment since we plan to switch back to use winit which has plans to add access to the event loop https://github.com/rust-windowing/winit/issues/2120

Alternatively, you could spawn a hidden window that you can manage its own event loop to fit your needs.

**Comment by imxood** [comment]
@amrbashir I use a thread to capture specific events through a hidden window to complete this function, thank you very much.
