### ISSUE TITLE
[feat] Add support for dpi on menu icons on macos

### ISSUE THREAD

**Issue by grant0417** [tauri-apps/tao#584]
When using the CustomMenuItem API in Tao on macOS there is no way to represent high DPI icons. Typically you'd do that with `@2x`, but the icons is just loaded into memory and thus doesn't have that context.

https://docs.rs/tao/latest/tao/menu/struct.CustomMenuItem.html#method.set_icon

![image](https://user-images.githubusercontent.com/7355421/194954457-10c173e7-b0eb-436d-a952-5dfc50641cf4.png)

**Comment by amrbashir** [comment]
could you try [`macos-menu-icon-h-18`](https://github.com/tauri-apps/tao/tree/macos-menu-icon-h-18) branch and see if it fixes the issue? 

<sub>I don't have a mac to test 😅</sub>
