### ISSUE TITLE
who can i create a window with muti child window,or muti webviews?

### ISSUE THREAD

**Issue by work-ixiaozi-cn** [tauri-apps/tao#616]
who can i create a window with muti child window,or muti webview?

**Comment by amrbashir** [comment]
You can use https://docs.rs/tao/latest/x86_64-pc-windows-msvc/tao/platform/windows/trait.WindowBuilderExtWindows.html#tymethod.with_parent_window to create multi childs in one window on Windows, other platforms have different ways to do it but not included in tao and probably will not. As for multi-webview, see #https://github.com/tauri-apps/wry/issues/677
