### ISSUE TITLE
Update `tray` menu items

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/tao#63]
We should have the option to rebuild the tray menu after the app is launched.

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by fnune** [comment]
Hey, I've been taking a look at the new API in `1.0.0-beta.2`. It looks great!

However, I think you added `set_icon` to `SystemTrayHandle`, but not `set_menu`?

I can take a look at implementing it myself, just want to make sure that this is indeed the case and we want `set_menu`.

**Comment by fnune** [comment]
I saw you're doing this for Windows (https://github.com/tauri-apps/tao/pull/93), so I gave it a go on Linux: https://github.com/tauri-apps/tao/pull/106
