### ISSUE TITLE
Add event about `maximize` and `unmaximize`

### ISSUE THREAD

**Issue by CGQAQ** [tauri-apps/tao#633]
Add event about `maximize` and `unmaximize`  so I can change maximize button icon dynamically
![image](https://user-images.githubusercontent.com/15936231/204453149-c7fb7e66-fd50-40db-a6a8-fbc7002a4d46.png)
![image](https://user-images.githubusercontent.com/15936231/204453311-d216fba5-c958-456d-b16e-8d4dc7282176.png)

**Comment by amrbashir** [comment]
Maximizing the window should fire the `resize` event, so you can listen to that and update the button accordingly.

**Comment by CGQAQ** [comment]
@amrbashir what if maximize without changing content area size? At least you can do that on Windows, macOS is different story though

**Comment by amrbashir** [comment]
On Windows, maximizing fires `WM_SIZE` which we use to dispatch a `resize` event.

**Comment by CGQAQ** [comment]
> On Windows, maximizing fires `WM_SIZE` which we use to dispatch a `resize` event.

Oh! Thanks! I’ll try it tomorrow

**Comment by amrbashir** [comment]
Please try `resize` event, if it doesn't work well enough for you on all platforms, I will reconsider implementing a `Maximize` event

**Comment by CGQAQ** [comment]
> Please try `resize` event, if it doesn't work well enough for you on all platforms, I will reconsider implementing a `Maximize` event

Ok, thanks a lot

**Comment by amrbashir** [comment]
> macOS is different story though

true, Windows and Linux are pretty easy to implement, macOS is a bit trickey.

**Comment by ChaserZ98** [comment]
Abusing the resize event for checking a maximize event causes some problems as tauri-apps/tauri#6754 shows. Maybe it is time to reopen this issue? @amrbashir
