### ISSUE TITLE
` Cannot bind shortcut key

### ISSUE THREAD

**Issue by cosoc** [tauri-apps/tao#636]
Theoretically, any valid key on the keyboard should be able to be bound

https://github.com/tauri-apps/tao/issues/147  But has been closed

**Comment by amrbashir** [comment]
Shortcuts have been removed from `tao`, and have been moved to [`global-hotkey`](https://github.com/tauri-apps/global-hotkey) crate, if you still can't bind a certain key, please open an issue there
