### ISSUE TITLE
Implement ability to change the system tray icon during runtime

### ISSUE THREAD

**Issue by fnune** [tauri-apps/tao#64]
Many apps (for an easy example: Slack) change their system tray icon depending on app state.

I believe it's not possible to do this in Tauri, because systsem tray icons are defined statically in `tauri.conf.json`. It would be nice to be able to change the icon in the app runtime.

**Comment by lemarier** [comment]
Note; We need to implement a setter on the tray where we save the pointer of the OS tray icon. (`HWND`, `Object` id). We could simply update the icon without rebuilding the whole tray.

https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/macos/system_tray.rs#L48
https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/windows/system_tray.rs#L105
https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/linux/system_tray.rs#L31
