### ISSUE TITLE
Show images in system tray menu items

### ISSUE THREAD

**Issue by fnune** [tauri-apps/tao#645]
Hi there, I'm wondering if it's at all possible to show images next to menu items. For example, see the Zoom and co. icons on [MeetingBar](https://github.com/leits/MeetingBar):

![image](https://user-images.githubusercontent.com/16181067/207469743-222e98c6-e603-424a-9807-601ba859f404.png)

It seems possible on Mac. I'm particularly interested in Linux, though. I'd be open to try and implement this. Although only a bit, I've contributed to Tao in the past.

Thanks for your amazing work :bow:

**Comment by amrbashir** [comment]
This have been implemented in for macOS, and I previously implemented it for Windows. As for Linux, we could use https://docs.gtk.org/gtk3/class.ImageMenuItem.html but it has been deprecated.

I should also note that we have stopped working on the menu system in tao and wrote a new crate for menus https://github.com/tauri-apps/muda which will be used by Tauri in v2

**Comment by fnune** [comment]
Thanks for the context. Looking forward to Muda!

**Comment by fnune** [comment]
I found a workaround for `ImageMenuItem`:

```rust
let mut menu = gtk::Menu::new();
                                                                                             
// A bit of a hack: this defaults to `false` in most "modern" (2010+ or so) DEs. This line
// enables menu images just for this application.
let settings = gtk::Settings::default().unwrap();
glib::ObjectExt::set_property(&settings, "gtk-menu-images", true);
                                                                                             
// One used to be able to instantiate an ImageMenuItem, but now one needs to build a box and
// pack some children instead:
let image = gtk::Image::from_file(icon_path.join("icon.png"));
let label = gtk::Label::new(Some("Hi there"));
                                                                                             
let mut menu_item_box = gtk::Box::builder().build();
menu_item_box.pack_start(&image, true, true, 0);
menu_item_box.pack_start(&label, true, true, 0);
                                                                                             
menu_item_box.show_all();
                                                                                             
let menu_item = gtk::builders::MenuItemBuilder::new().child(&menu_item_box).build();
menu.append(&menu_item);
                                                                                             
indicator.set_menu(&mut menu);
menu.show_all();
                                                                                             
gtk::main();
```

It works, and it seems to be the supported workaround also. Only drawback is one needs to set the `gtk-menu-images` GTK setting for the app, so that would probably require a `tauri.conf.json` setting.

I'll reopen the issue and leave it up to you to decide whether this is desirable for Tauri's Linux support.

**Comment by amrbashir** [comment]
yeah, this seems like an acceptable solution, however, I still won't put any efforts in tao's menu system and would rather implement it directly in muda.

**Comment by fnune** [comment]
Would you like me to raise an issue over there?

**Comment by amrbashir** [comment]
yeah sure, thank you

**Comment by amrbashir** [comment]
I will close this issue since this won't implemented here but in muda.

**Comment by Andrew-web-coder** [comment]
@amrbashir And? Where is the solution? Where are exampeles? What is muda?

**Comment by fnune** [comment]
@Andrew-web-coder please read the issue comments:

![image](https://github.com/tauri-apps/tao/assets/16181067/3bd76403-4e26-4d6b-8ed8-f652fb077c1c)

**Comment by Andrew-web-coder** [comment]
What is GTK? I am using Windows (and creating tray using `tauri::SystemTray`). 

Also, I do not understand why it is so difficult to provide one fully working demo. It is so easy to create tray menu using Electron (https://www.electronjs.org/docs/latest/api/tray), but with Tauri... it is a complete mystery/nightmare, simply because a lack of documentation or any useful demo.

**Comment by Andrew-web-coder** [comment]
So, is it possible to "Show images in system tray menu items" in Windows? How?

**Comment by amrbashir** [comment]
@Andrew-web-coder muda are a lower level crate that will be used by tauri, you don't need to use it yourself. It is however will be supported in v2 only and not be supported in tauri v1 due to breaking changes that we can't roll out in v1.
Also note that v2 will have a JS API that could be easier for you to use than Rust.
If you need help with something, I suggest reaching out to us on Discord.
