### ISSUE TITLE
Question about the LICENSE file

### ISSUE THREAD

**Issue by srevrtt** [tauri-apps/tao#647]
Hello. The LICENSE file in the root directory of tao has last been updated 9 years ago (2014). It also does not show the the copyright year and owner. 

_Here is a screenshot of what this looks like:_
![image](https://user-images.githubusercontent.com/94027678/207722033-7b141bbd-7346-40c7-86a8-a7e1d2017304.png)

Is this intentional or is this a mistake? Or is it on my end for whatever reason? Thanks.

**Comment by amrbashir** [comment]
This is the original license of the [`winit`](https://github.com/rust-windowing/winit/) project, because tao is a fork of winit. cc @nothingismagick since I don't know much about licensing.

**Comment by srevrtt** [comment]
That makes sense. Looking at [winit's LICENSE file](https://github.com/rust-windowing/winit/blob/master/LICENSE), I can see that it is the exact same. I guess I should have known beforehand as tao wasn't in development in 2014 :laughing:. Thanks for clarifying.
