### ISSUE TITLE
[MacOS] Handling CFBundleURLSchemes

### ISSUE THREAD

**Issue by elpiel** [tauri-apps/tao#653]
From our extend research in the past days we realised that it's not possible with `tao` nor `cocoa`, at this point, to add an event callback for handling `CFBundleURLSchemes`.
[fruitbasket](https://crates.io/crates/fruitbasket) does have support to add such callbacks, however, I'm not familiar enough with MacOS and it seems that the core loop should be in the main thread and we can't run 2 event loops (1 from tao and 1 from fruitbasket) to add this support in our application.

What would be a good way to add support to `tao` for this platform-specific case?

**Comment by FabianLars** [comment]
This is not a simple question. winit tried to find a way for _years_ at this point. Most relevant discussion/tracking issue: https://github.com/rust-windowing/winit/issues/2120

tao will use whatever winit will use (we plan to deprecate tao in favor of winit when it's possible), so if you want to bring this forward i'd suggest taking part of the discussion over there.

**Comment by elpiel** [comment]
On low level, registering a handler is callback based and does not depend on the event loop, we used [`fruitbasket`](https://crates.io/crates/fruitbasket) to create an App without running the event loop but registering our callback for handling the custom URL scheme.
