### ISSUE TITLE
Setting min or max size clears the other

### ISSUE THREAD

**Issue by sekwah41** [tauri-apps/tao#657]
If you use set_min_size it seems to clear whatever was set with set_max_size and vice versa.

**Comment by amrbashir** [comment]
Please post your OS info, and if possible, a minimal repro.

**Comment by sekwah41** [comment]
Ah yes sorry, its Linux on Manjaro. Ill create a repo later with an example.

**Comment by sekwah41** [comment]
https://github.com/sekwah41/resize-test here ya go, ive added two buttons to test triggering it. When you click one the other seems to be removed so you can only have a min or a max. Not both. On manjaro at least.
