### ISSUE TITLE
Add more variants or options to SystemTrayMenuItem

### ISSUE THREAD

**Issue by fnune** [tauri-apps/tao#66]
This requires some API design, but I'm missing some functionality in the tray items:

- A menu item that's not clickable but contains text.
- Alternatively, an option for the `Custom` menu item that makes it not clickable. The options could be extended to accept different styles somehow?

This all sounds hard to make cross-platform.

**Comment by lemarier** [comment]
You think having an option to disable any menu item may work?

Edit; like this (we could do it cross-platforms)
![image](https://user-images.githubusercontent.com/22237916/118790913-31ff7e00-b864-11eb-9a33-ed96505403a8.png)

**Comment by fnune** [comment]
I think you may be better informed: I have no idea about cross-platform desktop app development, so I don't know the limitations of GTK and the proprietary counterparts.

A `disabled` option would solve my use case, though!
