### ISSUE TITLE
WindowEvent::DroppedFile doesn't get emitted

### ISSUE THREAD

**Issue by TheBrenny** [tauri-apps/tao#675]
**Describe the bug**
After an exhaustive day of testing this and it's peer events (hover and hover cancelling), as well as Googling for answers on how to make it work, it appears that there's no clear description as to why the DroppedFile event never actually emits.

My project is a NodeJS wrapper around Wry, but seeing as Wry taps into Tao, I felt that this is the more logical repo for this issue.

**Steps To Reproduce**
Build a WebView using Wry using any template, and within the Event Loop's match block, add `Event::WindowEvent { event: WindowEvent::DroppedFile, .. } => println!("it fired!")`. Run, and drop a file, and expect nothing to appear in the console.

**Expected behavior**
Instead of needing to implement a separate file drop handler (which is a Wry-specific thing), I should be able to capture the DroppedFile events from within the Event Loop.

**Platform and Versions (please complete the following information):**
OS: Windows 11 Pro, `10.0.22621`
Rustc: `rustc 1.66.0 (69f9c33d7 2022-12-12)`

**Would you want to assign yourself to resolve this bug?**
- [ ] Yes
- [x] No (I wouldn't know where to start, and this seems too complex of a Rust problem for me to solve effectively.)

**Comment by amrbashir** [comment]
The problem is that the you need to catch drop events on the webview itself not the window and by doing so we disable the tao drop files handler and only wry's handler is active, so you need to use wry's https://docs.rs/wry/latest/wry/webview/struct.WebViewBuilder.html#method.with_file_drop_handler and you can use the event loop proxy to send a custom event to the event loop if you need to handle the drop file info from within the event loop.

**Comment by TheBrenny** [comment]
> and you can use the event loop proxy to send a custom event to the event loop if you need to handle the drop file info from within the event loop

It's annoying that this was the last thing I thought of right now after I posted this issue. I guess it's the best I can do for now...

But I'm curious, why not let the tao handler/event emitter stay functional? I noticed that after implementing wry's `.with_file_drop_handler`, my inspector stopped logging the drop events. I'd be tempted to say that only one drop handler can be active at a time - is this correct?

**Comment by amrbashir** [comment]
> I'd be tempted to say that only one drop handler can be active at a time - is this correct?

yes, at least on Windows right now. I am waiting for https://github.com/MicrosoftEdge/WebView2Feedback/issues/2907 so I can explore multiple drop handlers again.
