### ISSUE TITLE
`monitor::cursor_position()` not displaying correct cursor position

### ISSUE THREAD

**Issue by brettinternet** [tauri-apps/tao#707]
**Describe the bug**
Hi, I have two monitors stacked vertically on macOS.

```
🖥️   <-- cursor here where should be -1440 < y < 0
🖥️
```

However, when I have the cursor on the top monitor, I'm seeing a positive value which seems to indicate a distance from the bottom edge of the bottom monitor instead of from where the monitor starting axis is `(0, 0)`.

**Steps To Reproduce**

```rs
let cursor = PhysicalPosition { x: 397.55078125, y: 2035.25 }; // Cursor here is positioned above the primary monitor, and y should be negative
assert_eq!(cursor, window.cursor_position());
assert_eq!(window.monitor_from_point(cursor.x, cursor.y), None);
```

Then, I'm not able to find `window.monitor_from_point(cursor.x, cursor.y)` because here are my monitors:

```rs
let monitors = [
  MonitorHandle { inner: MonitorHandle { name: Some("Monitor #..."), native_identifier: 2, size: PhysicalSize { width: 2560, height: 1440 }, position: PhysicalPosition { x: 0, y: 0 }, scale_factor: 1.0 } },
  MonitorHandle { inner: MonitorHandle { name: Some("Monitor #..."), native_identifier: 5, size: PhysicalSize { width: 2560, height: 1440 }, position: PhysicalPosition { x: 0, y: -1440 }, scale_factor: 1.0 } },
];
assert_eq!(monitors, window.available_monitors());
```

**Expected behavior**
In my example, the cursor `y` position should be `-1440 < y < 0`. The cursor position appears to use a different `PhysicalPosition` axis than the position calculation for monitors.

**Platform and Versions (please complete the following information):**
OS: `macOS 13.2 (22D49)`
Rustc: `rustc 1.61.0 (fe5b13d68 2022-05-18)`
tao: `"0.18"`

**Workaround**

[This snippet from `rustdesk`](https://github.com/rustdesk/rustdesk/blob/8b3c4d3d642df5e7dd346294ac058a79753e06dc/src/platform/macos.rs#L242-L257) appears to be a decent workaround.

**Comment by wusyong** [comment]
I don't have a second monitor for mac. But perhaps airplay can reproduce this? I'll give it a try next week.
