### ISSUE TITLE
`window.cursor_position()` is actually `LogicalPosition`

### ISSUE THREAD

**Issue by 2e0byo** [tauri-apps/tao#708]
**Describe the bug**
`Window.cursor_position()` returns a `PhysicalPosition` which has to be multiplied by the scale factor to get the same value as the `CursorMoved` event.  Thus `Window.cursor_position()` is a different value from `CursorMoved` if scaling is in use.

This occurs at least on Hyprland on linux.

`CursorMoved` explicitly handles the conversion to PhysicalPosition [here](https://github.com/tauri-apps/tao/blob/28b53f80c49bbf2ae8902b98a2e28f6451a5a8f1/src/platform_impl/linux/event_loop.rs#L580).

**Steps to reproduce**
I don't have a MWE but could probably get one together.  This was discovered in EmacsNG (too large to compile just to reproduce).  Credit to @declantsien for working out what the problem was.

**Expected behavior**
Positions should be identical.

**Platform and Versions (please complete the following information):**
OS: Linux 6.2.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 26 Feb 2023 03:39:23 +0000 x86_64 GNU/Linux
Rustc: rustc 1.69.0-nightly (7aa413d59 2023-02-19)

**Would you want to assign yourself to resolve this bug?**
- [x] Yes
- [ ] No

**Additional context**
I don't know if this occurs on other platforms. Windows makes an [os call](https://github.com/tauri-apps/tao/blob/28b53f80c49bbf2ae8902b98a2e28f6451a5a8f1/src/platform_impl/windows/util.rs#L235-L244) as does [Mac](https://github.com/tauri-apps/tao/blob/28b53f80c49bbf2ae8902b98a2e28f6451a5a8f1/src/platform_impl/macos/util/mod.rs#L127-L132).  But linux goes via 
the [gdk Display](https://github.com/tauri-apps/tao/blob/28b53f80c49bbf2ae8902b98a2e28f6451a5a8f1/src/platform_impl/macos/util/mod.rs#L127-L132).  I'm guessing the seat returns a scaled position as I can't find anything in the gdk docs.

**Comment by wusyong** [comment]
I think I need an MWE to see if that's actually happen in tao. I thought GDK should handles that already.

**Comment by wusyong** [comment]
Okay, I tested in #711 and looks like they are wrong indeed. They are actually logical positions.

**Comment by 2e0byo** [comment]
great, thanks!  Sorry, I'm snowed under and hadn't got round to this.
