### ISSUE TITLE
macOS Window Content Edit State

### ISSUE THREAD

**Issue by markusmoenig** [tauri-apps/tao#716]
On macOS the state of the window content (if edited or not) is indicated by a small cross in the red close circle of the Window.

I cannot seem to edit this with tao. Could this possibly be added in a future version ?

Thanks

**Comment by amrbashir** [comment]
it is already supported https://github.com/tauri-apps/tao/blob/226756f0ac7520d4d2fb051dde9598238398246f/src/platform/macos.rs#L59-L65
I think our docs for macOS is failing to publish to docs.rs but here is an example: 
```rs
use tao::platform::macos::WindowExtMacOS;

window.set_is_document_edited(true);
```

**Comment by markusmoenig** [comment]
Thanks! The Docs are indeed not up to date. Great work on Tao!
