### ISSUE TITLE
Tao backport to 0.16 for Tauri v1.x.x

### ISSUE THREAD

**Issue by corentin35000** [tauri-apps/tao#739]
I have a problem when compiling with Windows x86 with the 'tao' package in version 0.16.1, you fixed it in version 0.20.0
I request the back port to 0.16.1 for Tauri v1.x.x

**Comment by amrbashir** [comment]
fixed in https://github.com/tauri-apps/tao/commit/0e950f8263ff349504285b68d51c7850146549d5

**Comment by amrbashir** [comment]
It is released now.
