### ISSUE TITLE
How to use Tao eventloop in Tauri ?

### ISSUE THREAD

**Issue by JinSooo** [tauri-apps/tao#791]
**Describe the bug**
I have no problem using it according to the example, but after executing eventloop, the frontend can no longer send messages to the backend, the thread is blocked!

**Steps To Reproduce**
in rust
```rust
#[tauri::command]
fn init_listen(_: tauri::AppHandle, window: tauri::Window) {
    // init_hotkey(window);

    let event_loop = EventLoop::new();
    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;
        // *control_flow = ControlFlow::Wait;
        println!("{:?}", event);
    })
}
```

frontend
```typescript
invoke('init_listen')
// ...
const path = await import('@tauri-apps/api/path')
console.log(await path.resourceDir()) // It's blocked!!!
```

**Platform and Versions (please complete the following information):**
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 116.0.1938.62
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ Cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.12.1
    - pnpm: 8.5.0
    - yarn: 1.22.19
    - npm: 9.8.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0   
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App

**Comment by FabianLars** [comment]
Try making the tauri command an async fn so it doesn't run on the main thread (this is what is blocking your frontend). For this to work you may have to use [`with_any_thread`](https://docs.rs/tao/latest/x86_64-pc-windows-msvc/tao/platform/windows/trait.EventLoopBuilderExtWindows.html#tymethod.with_any_thread) but it _may_ still complain about nested event loops since tauri already includes a tao event loop. This would probably not be the last hurdle so tbh i'd recommend not trying to do this at all.

**Comment by JinSooo** [comment]
I know about the with_any_thread function, but it's not compatible with macOS, so I didn't use it.
You said tauri has a tao event loop inside, is there any way to get it or use it?

**Comment by FabianLars** [comment]
> I know about the with_any_thread function, but it's not compatible with macOS, so I didn't use it.

welp, then you're probably really out of luck without multiple explicit processes.

> You said tauri has a tao event loop inside, is there any way to get it or use it?

Nope, only what's explicitly exposed can be used so if there's something missing tell us about it and of course we always appreciate PRs :)

**Comment by JinSooo** [comment]
Ok, fine.
I'd like to ask something else.
[https://github.com/tauri-apps/global-hotkey/blob/dev/examples/tao.rs](https://github.com/tauri-apps/global-hotkey/blob/dev/examples/tao.rs)
Here's what I'm trying to accomplish
If the envent loop doesn't work, is there another way to listen?

**Comment by FabianLars** [comment]
I'm not too familiar with that crate but maybe tauri's [run_iteration](https://docs.rs/tauri/latest/tauri/struct.App.html#method.run_iteration) is enough? If not, i guess you can also use set_event_handler and use a traditional channel to send it to _wherever_.

**Comment by FabianLars** [comment]
Here's an example of the event handler from the official v2 plugin: https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/global-shortcut/src/lib.rs#L303

**Comment by JinSooo** [comment]
> Here's an example of the event handler from the official v2 plugin: https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/global-shortcut/src/lib.rs#L303

That's a good way to go.
I wanted to use also GlobalShortCut at first, but it seems that there is no exposure to use it directly, only a trait. if you want to use it you can only go to call it on the front end.

**Comment by JinSooo** [comment]
I solved the problem using `set_event_handler`, thank you very much!!!!
