### ISSUE TITLE
Window content using pure Rust

### ISSUE THREAD

**Issue by AlexanderDKazakov** [tauri-apps/tao#879]
I compiled example of single window from `examples`:

```rust
// Copyright 2014-2021 The winit contributors
// Copyright 2021-2023 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0

use tao::{
  event::{Event, WindowEvent},
  event_loop::{ControlFlow, EventLoop},
  window::WindowBuilder,
};

#[allow(clippy::single_match)]
fn main() {
  let event_loop = EventLoop::new();

  let mut window = Some(
    WindowBuilder::new()
      .with_title("A fantastic window!")
      .with_inner_size(tao::dpi::LogicalSize::new(300.0, 300.0))
      .with_min_inner_size(tao::dpi::LogicalSize::new(200.0, 200.0))
      .build(&event_loop)
      .unwrap(),
  );

  event_loop.run(move |event, _, control_flow| {
    *control_flow = ControlFlow::Wait;
    println!("{:?}", event);

    match event {
      Event::WindowEvent {
        event: WindowEvent::CloseRequested,
        window_id: _,
        ..
      } => {
        // drop the window to fire the `Destroyed` event
        window = None;
      }
      Event::WindowEvent {
        event: WindowEvent::Destroyed,
        window_id: _,
        ..
      } => {
        *control_flow = ControlFlow::Exit;
      }
      Event::MainEventsCleared => {
        if let Some(w) = &window {
          w.request_redraw();
        }
      }
      _ => (),
    }
  });
}
```

<img width="412" alt="изображение" src="https://github.com/tauri-apps/tao/assets/17707394/16ca1215-27ed-467a-baac-02863b5f2a9e">

It functions as expected, but I'm wondering if it's possible to incorporate text or images into the window using only Rust. I am okay with having just one image on the window. 

I have searched for an extension to tao that might allow this (like `apply_vibrancy(&window, ...)` using the extention), but I have not been able to find anything. There are tips with extra files with certain schema and etc., but I am wondering if it possible to have something like 
```rust 
w.add_text("Something");
w.add_image(include_bytes!(...));
or 
```rust
w.add_html(...)
```

Any help is appreciated.

**Comment by amrbashir** [comment]
Unfortunately this is not the responsibility of this crate, you're probably better using `winit` crate (which `tao` was forked from) with one of these rendering crates:
- glutin
- wgpu


Or a full-feature UI crate:
- egui
- freya
- slint
- iced
- druid

Also take a look at https://areweguiyet.com/
