### ISSUE TITLE
Support visibility events

### ISSUE THREAD

**Issue by Legend-Master** [tauri-apps/tao#892]
**Is your feature request related to a problem? Please describe.**

Mainly for fixing https://github.com/tauri-apps/tauri/issues/6864

We need visibility events for sending it to the Windows WebView

> https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2controller?view=webview2-winrt-1.0.2365.46#isvisible

This will probably benefit people who's trying to do something when the window gets hidden and restored as well

**Describe the solution you'd like**

Support visibility change events

**Describe alternatives you've considered**

Or expose events like `Minimized`, `Restored`, `Show`, `Hide` separately

**Comment by amrbashir** [comment]
The OS doesn't emit `Show` and `Hide` events at all. As for minimize and restored events, there is no need to expose these as there is no dedicated events for them either but those can be checked in the already exposed `Resize` event by checking if `window.is_minimized()`

**Comment by Legend-Master** [comment]
Alright, didn't know show and hide events are not exposed by Windows
