### ISSUE TITLE
Base on GTK4 [feat] [linux]

### ISSUE THREAD

**Issue by Captainpast** [tauri-apps/tao#907]
**Describe the solution you'd like**
use for Linux/Unix platform, the newer GTK4 instead of GTK3

**Additional info**
https://docs.gtk.org/gtk4/migrating-3to4.html

_Originally posted by @Captainpast in https://github.com/tauri-apps/tauri/issues/9458#issuecomment-2054010186_

**Comment by amrbashir** [comment]
we don't plan on migrating to GTK4 at anytime soon because we need to use libayatana-indicator for tray and it doesn't support GTK4 atm
