### ISSUE TITLE
window::Window::is_maximised does not return the current state of the window

### ISSUE THREAD

**Issue by RobertasJ** [tauri-apps/tao#932]
**Describe the bug**
window::Window::is_maximised does not return the current state of the window, it instead returns a value that it set on creation of the Window object. 

**Steps To Reproduce**
Run the is_maximized, change from maximized to normal, or from normal to maximized and run the is_maximized method again. the function will give back the same value.

**Expected behavior**
for the is_maximized function to instead run self.window.is_maximized. as of now it gives back a stored value on initialization.

**Platform and Versions (please complete the following information):**
OS: Linux
Rustc: rustc 1.78.0 (9b00956e5 2024-04-29)

**Additional context**
This makes it impossible to track whether or not the window is maximized effectively. If there is a reason for it to give back the value on initialization, please provide.

edit: there are a few more functions that have the same behaviour, for example: is_minimized, inner_position, outer_position, scale_factor, inner_size, outer_size.

**Comment by amrbashir** [comment]
This is partially true, the `Window` struct contains a clone of an `AtomicBool` which will be updated in another callback in https://github.com/tauri-apps/tao/blob/b1b8b3ffac3dcd98c92e0d0010a49c5dc43e40c0/src/platform_impl/linux/window.rs#L264, same is done for other getters as well. 

Can you show a reproduction where it is not behaving as expected? Also what Desktop environment you're running?

**Comment by RobertasJ** [comment]
Im sorry for the false report, it seems that the way i tried to retrieve the state was not functioning correctly and wasnt outputting the current value, which led me to looking at the code, missing the callback and coming to the conclusion that there is nothing that updates the state after initialization. I hope this wasn't a big inconvenience, but may i ask, are there events for when these values change? I have been looking for a way to do this without retrieving the data at some set intervals.

**Comment by amrbashir** [comment]
Without a code example of what you're trying to do, I can't really suggest that much but generally `Resize` event will be triggered when maximizing a window, so maybe check there.

**Comment by RobertasJ** [comment]
Ah, so there isnt a concrete event, like WindowMaximized or anything simmilar. Well i think im going to close this issue here.
