### ISSUE TITLE
Use DBus instead of unity

### ISSUE THREAD

**Issue by flying-sheep** [tauri-apps/tao#962]
First and foremost, the following check is wrong: KDE Plasma also supports libunity’s DBus calls, so when you call progressbar APIs on KDE Plasma (either through libunity or DBus directly), it works. So even if you don’t switch to DBus, remove this check. Generally you should rather do feature discovery than gating features behind a desktop type.

https://github.com/tauri-apps/tao/blob/1113935fb83b5e1c2455b4ae82fc2bf0bab71c82/src/platform_impl/linux/taskbar.rs#L131-L138

But the better option is to use the DBus API: https://wiki.ubuntu.com/Unity/LauncherAPI#Low_level_DBus_API:_com.canonical.Unity.LauncherEntry

(ignore the warning about libunity being more stable than it: libunity isn’t really being maintained anymore, so the DBus API should be considered stable)

**Comment by amrbashir** [comment]
we did use DBus in the past, but was removed because the `zbus` crate was bloated and added a bit of size to the final binary (around 300kb but don't hold me to it).

**Comment by amrbashir** [comment]
I think we can just remove this supported check altogether and it should work fine for any distro that has libunity

**Comment by flying-sheep** [comment]
They seem to be working on it: https://github.com/dbus2/zbus/issues/304#issuecomment-2144780012

But yeah, for the time being, removing the check is a big step forward. Maybe people will actually end up building a standardized successor protocol that can be used, e.g.: https://github.com/flatpak/xdg-desktop-portal/discussions/1276

**Comment by flying-sheep** [comment]
Great, thank you!
