### ISSUE TITLE
Dropping files doesn't work on Windows

### ISSUE THREAD

**Issue by Boscop** [tauri-apps/tao#986]
**Problem**

Dropping files doesn't work on Windows, the event doesn't seem to get triggered.

**Steps To Reproduce**

- git clone https://github.com/DioxusLabs/dioxus.git (Dioxus uses tao)
- `cargo r --example file_upload`
- Click on "Choose Files" (the file input) and select a .txt file -> That works fine but:
- Now click "Clear Files" and drag the same .txt file from Windows Explorer and drop it onto the "Drop files here" area
- Nothing happens!

**Expected behavior**

It should load the file just like when opening it by clicking on the file input and selecting it through the file dialog.

**Screenshots**

![image](https://github.com/user-attachments/assets/a6dea390-58c4-482b-bd06-31362af16be0)

**Environment:**
 - Dioxus version:  latest `main` branch, commit `b20db13e84227b76741e007b2763adc8237ada48`
 - Rust version:    `rustc 1.82.0-nightly (8b3870784 2024-08-07)`
 - OS info:         Windows 11
 - App platform:    desktop

---

Btw, someone else [confirmed](https://github.com/DioxusLabs/dioxus/issues/2954#issuecomment-2351223067):
> I can verify that this does not work on Windows 10, Dioxus main.

**Comment by amrbashir** [comment]
The tao drag and drop events work just fine on Windows, you can run `cargo run --example window` and drag a file onto the window, and the event will be logged. 

I think dioxus is using `wry` as well, and in that case you might be looking for https://docs.rs/wry/latest/wry/struct.WebViewBuilder.html#method.with_drag_drop_handler

**Comment by Boscop** [comment]
@amrbashir Ah thanks, I just tried the `window` example, and it logs the event, but only with path, not with position..
I guess `wry` constructs the higher level `DragDropEvent` by keeping track of `CursorMoved` events so know the cursor position at the time of `DroppedFile`.
So yeah this must be a dioxus bug then..

---

Btw, in the CLI-generated tauri leptos template, how can I get access to the `WebViewBuilder` so that I can call the `with_drag_drop_handler` method?
There is only one mention of "builder" in the whole workspace, and it's `tauri::Builder` but only in the mobile entrypoint:

<img width="740" alt="{E4D43629-E9C4-42A4-996A-CBB6D4CB2B47}" src="https://github.com/user-attachments/assets/ca1043b5-87c5-4156-8e36-7308a328bd30">

**Comment by amrbashir** [comment]
@Boscop apologies for the late reply, you seem to be using Tauri, in which case there is no similar callback as the one provided in wry. Instead there is [`DragDropEvent`](https://docs.rs/tauri/latest/tauri/enum.DragDropEvent.html) which can be listened to in [`on_window_event`](https://docs.rs/tauri/latest/tauri/struct.Builder.html#method.on_window_event), [`on_webview_event`](https://docs.rs/tauri/latest/tauri/struct.Builder.html#method.on_webview_event) (if using multi-webview when using `unstable` feature flag) or [`App::run`](https://docs.rs/tauri/latest/tauri/struct.App.html#method.run)
