### ISSUE TITLE
`Window::set_decorations(false)` prevents the window from being reliably drag-resized on Windows 

### ISSUE THREAD

**Issue by chipnertkj** [tauri-apps/tao#994]
**Describe the bug**
Disabling window decorations on Windows using `Window::set_decorations` or `WindowBuilder::with_decorations` with `false` causes issues with drag-resizing the window, as mentioned in https://github.com/tauri-apps/tauri/issues/7900. Removing the user's ability to resize the window as a result of disabling decorations does not sound like expected behavior. This also introduces an inconsistency where you're allowed to set both `.set_decorations(false)` and `.set_resizable(true)`, yet behavior does not reflect such usage. `tao` does not provide the required API to bring drag-resizing back to a window without decorations, either.

This behavior does not appear to be documented anywhere and prevents anyone from attempting to build an application that uses `tao` with the intent to create a custom title bar on Windows.

**Steps To Reproduce**
Create a window on Windows with decorations disabled. You may also manually enable resizing on the window, although it will have little effect. Attempt to drag-resize the window.

**Expected behavior**
User should be able to drag-resize the window without issues when using `.set_decorations(false)`.

**Screenshots**
See https://github.com/tauri-apps/tauri/issues/7900#issuecomment-1734677770 for a video depicting the issue.
Note: the video only showcases attempts made at the upper-right corner. On my end, I am also completely unable to resize the window unless im dragging from the upper edge of the window, in which case it is still difficult to grab onto - the area is one pixel high.

**Platform and Versions (please complete the following information):**
OS: Windows 10/11
Rustc: rustc 1.83.0-nightly (eb4e23467 2024-10-09)

**Additional context**
Curiously this doesn't appear to be a problem when using `"decorations": false` in `tauri.conf.json` with `tauri` - you can resize the window as expected. What is the reason for this discrepancy? This issue also appears when disabling decorations in `dioxus-desktop`, which makes sense as it directly exposes `tao` as part of its API.

**Comment by amrbashir** [comment]
Disabling decorations in `tao` doesn't affect resizability of the window at all, it is only when you add a webview on top of it (using wry, as it is done in tauri), that the `tao` window doesn't get access to the events necessary to resize the window.

However, tauri have its own resizing implementation that works even when the webview is layed on top of the `tao` window.

The linked video is a year old, please try tauri@v2 and the issue should be fixed.

**Comment by amrbashir** [comment]
I see that you mentioned dioxus in the other issue so here is how it is implemented in tauri, in case dioxus wants to replicate https://github.com/tauri-apps/tauri/blob/dev/crates/tauri-runtime-wry/src/undecorated_resizing.rs
