### ISSUE TITLE
Top border persists with decorations disabled

### ISSUE THREAD

**Issue by SpikeHD** [tauri-apps/tao#997]
**Describe the bug**
When disabling decorations (in order to use a custom titlebar), a single-pixel-wide border on the top is still visible. The border is either grey (and quite hard to spot, usually) when `Show the accent colour on the following surfaces -> Title bars and window borders` is disabled, or the system accent colour when the setting is enabled.

This can be seen in Tao's `decorations` example. You may have to look closely at the top of the white window:
![image](https://github.com/user-attachments/assets/335d9b69-bc77-4fb9-976c-00ea9f078286)

**Steps To Reproduce**
1. Optionally enable "Title bars and window borders" in Windows accent colour settings, in order to better see the effect
2. Create a Window with `with_decorations(false)`

**Expected behavior**
There should be no top border

**Screenshots**
In my project (for better visibility via the dark titlebar), using the custom titlebar (aka decorations off):
![image](https://github.com/user-attachments/assets/ff343f33-aea8-4dbf-9583-2de515c6aca3)

Using the system titlebar (aka decorations on):
![image](https://github.com/user-attachments/assets/297ff755-05bc-4463-8c76-61bad54a367b)

**Platform and Versions (please complete the following information):**
OS: Windows 10 22H2 19045.5011
Rustc: `1.81.0`

**Additional Context**
https://github.com/SpikeHD/Dorion/issues/268

**Comment by amrbashir** [comment]
this should be fixed by #993 where all 4 sides will have borders which matches the native system behavior, if you want that disabled as well, you'll need to also disable `shadows`.
